In [1]:
from vnstock import register_user
register_user()

📦 **Vnstock 3.5.0 is available**
Current version: 3.4.2
Update: `pip install vnstock --upgrade`
Release history: https://vnstocks.com/docs/tai-lieu/lich-su-phien-ban

📦 **Vnai 2.4.0 is available**
Current version: 2.3.9
Update: `pip install vnai --upgrade`
Release history: https://pypi.org/project/vnai/#history

======================================================================
  VNSTOCK - ĐĂNG KÝ API KEY
======================================================================
✓ API key: vnstock_1dfd293...
✓ Tier (Gói): free
✓ Giới hạn (Limits): {'per_minute': 60, 'per_hour': 3600}

✓ API key: vnst***3...
✓ Tier (Gói): free
✓ Giới hạn (Limits): {'per_minute': 60, 'per_hour': 3600}

True

In [2]:
# Import các module của vnstock
from vnstock import Listing, Quote, Company, Finance, Trading, Screener

# Cách khác: Import từ nguồn dữ liệu cụ thể
# from vnstock.explorer.vci import Listing, Quote, Company, Finance, Trading
# from vnstock.explorer.tcbs import Quote, Company, Finance, Trading, Screener

print("✅ Tất cả modules đã được import thành công!")

✅ Tất cả modules đã được import thành công!

In [3]:
# VCI là nguồn dữ liệu từ CK Vietcap bên cạnh nguồn từ TCBS
from vnstock import Listing
listing = Listing(source='KBS')

In [4]:
listing.all_symbols()

     symbol                                organ_name
0       MGC                    CTCP Địa chất mỏ - TKV
1       GVT                        CTCP Giấy Việt Trì
2       GEG                         CTCP Điện Gia Lai
3       SWC  Tổng Công ty cổ phần Đường sông Miền Nam
4       SLD                         CTCP Địa ốc Sacom
...     ...                                       ...
1540    PWA                 CTCP Bất động sản Dầu khí
1541    HSG                     CTCP Tập đoàn Hoa Sen
1542    DIC             CTCP Đầu tư và Thương mại DIC
1543    MEL                          CTCP Thép Mê Lin
1544    MCO      CTCP Đầu tư và Xây dựng BDC Việt Nam

[1545 rows x 2 columns]

In [5]:
# Liệt kê tất cả mã chứng khoán theo nhóm phân loại. Ví dụ HOSE, VN30, VNMidCap, VNSmallCap, VNAllShare, VN100, ETF, HNX, HNX30, HNXCon, HNXFin, HNXLCap, HNXMSCap, HNXMan, UPCOM, FU_INDEX (mã chỉ số hợp đồng tương lai), CW (chứng quyền)
listing.symbols_by_group('VN30')

0     ACB
1     BID
2     CTG
3     DGC
4     FPT
5     GAS
6     GVR
7     HDB
8     HPG
9     LPB
10    MBB
11    MSN
12    MWG
13    PLX
14    SAB
15    SHB
16    SSB
17    SSI
18    STB
19    TCB
20    TPB
21    VCB
22    VHM
23    VIB
24    VIC
25    VJC
26    VNM
27    VPB
28    VPL
29    VRE
Name: symbol, dtype: str

In [6]:
from vnstock import Finance
finance = Finance(symbol='VCB', source='KBS')

In [14]:
from vnstock import Finance
finance = Finance(symbol='ACB', source='KBS')
df = finance.balance_sheet(period='quarter')

In [8]:
import pandas as pd
# Show all rows
pd.set_option('display.max_rows', None)

In [9]:
df = finance.balance_sheet(period='quarter')

In [13]:
# 1. Delete the first column ('item')
df = df.iloc[:, 1:] 
# Alternatively: df = df.drop(df.columns[0], axis=1)

# 2. Set the now-first column ('item_id', which was originally the second column) as the index
df = df.set_index(df.columns[0])

# 3. Transpose the DataFrame (turn columns into rows and rows into columns)
df_transformed = df.T

# Display the result
df_transformed

item_id,assets,i.cash_gold_and_silver_precious_stones,ii.balances_with_the_state_bank_of_vietnam,iii.placements_at_and_loans_to_other_credit_institutions,n_1.placements_at_other_credit_institutions,n_2.loans_to_other_credit_institutions,n_3.provisions_for_losses_and_risks,iv.trading_securities,n_1.trading_securities,n_2.provisions_for_diminution_in_value_of_trading_securities,...,d.treasury_shares,e.preferred_stock,g.other_capital,n_2.reserves,n_3.foreign_exchange_differences,n_4.assets_revaluation_differences,n_5.undistributed_earnings_after_tax_accumulated_loss,n_6.minoritys_interest,ix.minority_interest,total_liabilities_and_owners_equity
2025-Q4,NaN,8.624548e+09,1.657496e+10,1.499907e+11,1.499907e+11,NaN,NaN,6.544882e+09,6.708358e+09,-163476000.0,...,NaN,NaN,NaN,1.758306e+10,NaN,NaN,2.529831e+10,NaN,NaN,1.025850e+12
2025-Q3,NaN,6.785568e+09,1.519747e+10,1.049259e+11,1.049259e+11,NaN,NaN,5.918486e+09,6.072639e+09,-154153000.0,...,NaN,NaN,NaN,1.478957e+10,-319534000.0,NaN,2.530712e+10,NaN,NaN,9.485492e+11
2025-Q2,NaN,6.666091e+09,5.439937e+09,1.254473e+11,1.254473e+11,NaN,NaN,4.958406e+09,5.160049e+09,-201643000.0,...,NaN,NaN,NaN,1.478957e+10,-243816000.0,NaN,2.102653e+10,NaN,NaN,9.335414e+11
2025-Q1,NaN,5.857654e+09,1.345751e+10,1.293475e+11,1.293475e+11,NaN,NaN,4.307534e+09,4.479661e+09,-172127000.0,...,NaN,NaN,NaN,1.478957e+10,-65367000.0,NaN,2.741202e+10,NaN,NaN,8.916746e+11

In [10]:
df

,item,item_id,2025-Q4,2025-Q3,2025-Q2,2025-Q1
0,A. TÀI SẢN,assets,NaN,NaN,NaN,NaN
1,"I. Tiền mặt, vàng bạc, đá quý",i.cash_gold_and_silver_precious_stones,8.624548e+09,6.785568e+09,6.666091e+09,5.857654e+09
2,II. Tiền gửi tại NHNN,ii.balances_with_the_state_bank_of_vietnam,1.657496e+10,1.519747e+10,5.439937e+09,1.345751e+10
3,"III. Tiền, vàng gửi tại các TCTD khác và cho v...",iii.placements_at_and_loans_to_other_credit_in...,1.499907e+11,1.049259e+11,1.254473e+11,1.293475e+11
4,"1. Tiền, vàng gửi tại các TCTD khác",n_1.placements_at_other_credit_institutions,1.499907e+11,1.049259e+11,1.254473e+11,1.293475e+11
5,2. Cho vay các TCTD khác,n_2.loans_to_other_credit_institutions,NaN,NaN,NaN,NaN
6,3. Dự phòng rủi ro cho vay các TCTD khác,n_3.provisions_for_losses_and_risks,NaN,NaN,NaN,NaN
7,IV. Chứng khoán kinh doanh,iv.trading_securities,6.544882e+09,5.918486e+09,4.958406e+09,4.307534e+09
8,1. Chứng khoán kinh doanh,n_1.trading_securities,6.708358e+09,6.072639e+09,5.160049e+09,4.479661e+09
9,2. Dự phòng giảm giá chứng khoán kinh doanh,n_2.provisions_for_diminution_in_value_of_trad...,-1.634760e+08,-1.541530e+08,-2.016430e+08,-1.721270e+08
10,V. Các công cụ tài chính phái sinh và các tài ...,v.derivatives_and_other_financial_assets,3.242980e+08,NaN,NaN,NaN
11,VI. Cho vay khách hàng,vi.loans_advances_and_finance_leases_to_customers,6.791526e+11,6.630324e+11,6.276694e+11,5.924308e+11
12,1. Cho vay và cho thuê tài chính khách hàng,n_1.loans_advances_and_finance_leases_to_custo...,6.867774e+11,6.691881e+11,6.337487e+11,5.988059e+11
13,2. Dự phòng rủi ro cho vay và cho thuê tài chí...,n_2.provisions_for_losses_on_loans_advances_an...,-7.624729e+09,-6.155708e+09,-6.079287e+09,-6.375105e+09
14,VII. Hoạt động mua nợ,vii.debt_purchased,NaN,NaN,NaN,NaN
15,1. Mua nợ,n_1.debt_purchased,NaN,NaN,NaN,NaN
16,2. Dự phòng rủi ro hoạt động mua nợ,n_2.provision_for_debt_purchased,NaN,NaN,NaN,NaN
17,VIII. Chứng khoán đầu tư,viii.investment_securities,1.441641e+11,1.337596e+11,1.457787e+11,1.299783e+11
18,1. Chứng khoán đầu tư sẵn sàng để bán,n_1.available_for_sales_securities,1.327788e+11,1.218534e+11,1.338628e+11,1.180528e+11
19,2. Chứng khoán đầu tư giữ đến ngày đáo hạn,n_2.held_to_maturity_securities,1.139653e+10,1.190619e+10,1.191586e+10,1.192552e+10
20,3. Dự phòng giảm giá chứng khoán đầu tư,n_3.provisions_for_diminution_in_value_of_inve...,-1.125000e+07,NaN,NaN,NaN
21,"IX. Góp vốn, đầu tư dài hạn",ix.capital_contribution_and_other_long_term_in...,7.469900e+07,1.267740e+08,1.248850e+08,1.267730e+08
22,1. Đầu tư vào công ty con,n_1.investments_in_subsidiaries,NaN,NaN,NaN,NaN
23,"2. Đầu tư vào công ty liên doanh, liên kết",n_2.investments_in_associates_joint_ventures,NaN,NaN,NaN,NaN
24,3. Đầu tư dài hạn khác,n_3.other_long_term_investments,2.337390e+08,2.928670e+08,2.928670e+08,2.928670e+08
25,4. Dự phòng giảm giá đầu tư dài hạn,n_4.provision_for_diminution_in_value_of_long_...,-1.590400e+08,-1.660930e+08,-1.679820e+08,-1.660940e+08
26,X. Tài sản cố định,x.fixed_assets,5.438550e+09,5.400704e+09,5.396553e+09,5.311943e+09
27,1. Tài sản cố định hữu hình,n_1.tangible_fixed_assets,3.200487e+09,3.209383e+09,3.223395e+09,3.148991e+09
28,a. Nguyên giá TSCĐ,a.cost,6.806108e+09,6.719862e+09,6.683909e+09,6.522507e+09
29,b. Hao mòn TSCĐ,b.accumulated_depreciation,-3.605621e+09,-3.510479e+09,-3.460514e+09,-3.373516e+09
30,2. Tài sản cố định thuê tài chính,n_2.finance_leased_fixed_assets,NaN,NaN,NaN,NaN
31,a. Nguyên giá TSCĐ,a.cost_2,NaN,NaN,NaN,NaN
32,b. Hao mòn TSCĐ,b.accumulated_depreciation_2,NaN,NaN,NaN,NaN
33,3. Tài sản cố định vô hình,n_3.intangible_fixed_assets,2.238063e+09,2.191321e+09,2.173158e+09,2.162952e+09
34,a. Nguyên giá TSCĐ,a.cost_3,3.117527e+09,3.040154e+09,2.991718e+09,2.950921e+09
35,b. Hao mòn TSCĐ,b.accumulated_depreciation_3,-8.794640e+08,-8.488330e+08,-8.185600e+08,-7.879690e+08
36,XI. Bất động sản đầu tư,xi.investment_properties,1.496730e+08,1.035440e+08,6.231000e+07,1.770050e+08
37,a. Nguyên giá BĐSĐT,a.cost_4,1.496920e+08,1.035440e+08,6.231000e+07,1.770050e+08
38,b. Hao mòn BĐSĐT,b.accumulated_depreciation_4,-1.900000e+04,NaN,NaN,NaN
39,"XII. Tài sản ""Có"" khác",xii.other_assets,1.481110e+10,1.329869e+10,1.199788e+10,1.067960e+10
40,1. Các khoản phải thu,n_1.accounts_receivables,6.743073e+09,5.907466e+09,4.914184e+09,3.769355e+09
41,"2. Các khoản lãi, phí phải thu",n_2.interest_and_fee_receivables,6.819629e+09,6.169586e+09,5.944745e+09,5.755801e+09
42,3. Tài sản thuế TNDN hoãn lại,n_3.deferred_income_tax_assets,1.726300e+07,3.633600e+07,5.604100e+07,5.752700e+07
43,4. Tài sản Có khác,n_4.other_assets,1.414349e+09,1.374696e+09,1.269621e+09,1.275976e+09
44,- Trong đó: Lợi thế thương mại,of_which_goodwill,NaN,NaN,NaN,NaN
45,5. Các khoản dự phòng rủi ro cho các tài sản C...,n_5.provisions_for_risks_in_other_assets,-1.832150e+08,-1.893920e+08,-1.867060e+08,-1.790640e+08
46,TỔNG CỘNG TÀI SẢN,total_assets,1.025850e+12,9.485492e+11,9.335414e+11,8.916746e+11
47,B. NỢ PHẢI TRẢ VÀ VỐN CHỦ SỞ HỮU,b.liabilities_and_owners_equity,NaN,NaN,NaN,NaN
48,I. Các khoản nợ Chính phủ và NHNN,i.due_to_government_and_borrowings_from_the_st...,3.297614e+10,2.069157e+10,2.102678e+10,1.864329e+10
49,II. Tiền gửi và vay các TCTD khác,ii.placements_and_borrowings_from_other_credit...,1.549995e+11,1.291761e+11,9.625927e+10,1.012841e+11
50,1. Tiền gửi của các TCTD khác,n_1.placements_from_other_credit_institutions,1.213141e+11,9.430945e+10,6.617527e+10,7.162934e+10
51,2. Vay các TCTD khác,n_2.borrowings_from_other_credit_institutions,3.368540e+10,3.486664e+10,3.008401e+10,2.965474e+10
52,III. Tiền gửi của khách hàng,iii.deposits_from_customers,5.851802e+11,5.710290e+11,5.674069e+11,5.503750e+11
53,IV. Các công cụ tài chính phái sinh và các kho...,iv.derivatives_and_other_financial_liabilities,NaN,1.236680e+08,3.188490e+08,1.713380e+08
54,"V. Vốn tài trợ, ủy thác đầu tư, cho vay mà TC...",v.funds_received_from_government_and_instituti...,1.907900e+07,2.245600e+07,2.454700e+07,2.672500e+07
55,VI. Phát hành giấy tờ có giá,vi.valuable_papers_e_g_bonds_cds,1.332944e+11,1.133871e+11,1.395528e+11,1.140518e+11
56,VII. Các khoản nợ khác,vii.other_liabilities,2.486105e+10,2.270387e+10,2.174164e+10,2.004773e+10
57,"1. Các khoản lãi, phí phải trả",n_1.interest_and_fee_payables,8.969078e+09,8.732073e+09,8.620225e+09,7.904161e+09
58,2. Thuế TNDN hoãn lại phải trả,n_2.deferred_income_tax_liabilities,NaN,NaN,NaN,NaN
59,3. Các khoản phải trả và công nợ khác,n_3.other_liabilities,1.589198e+10,1.397180e+10,1.312142e+10,1.214357e+10
60,4. Dự phòng rủi ro khác (Dự phòng cho công nợ ...,n_4.provisions_for_contingent_liabilities_and_...,NaN,NaN,NaN,NaN
61,TỔNG NỢ PHẢI TRẢ,total_liabilities,9.313304e+11,8.571337e+11,8.463308e+11,8.046000e+11
62,VIII. Vốn và các quỹ,viii.capital_and_reserves,9.451972e+10,9.141550e+10,8.721063e+10,8.707458e+10
63,1. Vốn của TCTD,n_1.capital,5.163834e+10,5.163834e+10,5.163834e+10,4.493836e+10
64,a. Vốn điều lệ,a.charter_capital,5.136657e+10,5.136657e+10,5.136657e+10,4.466658e+10
65,b. Vốn đầu tư XDCB,b.reserves_for_investments_in_construction,NaN,NaN,NaN,NaN
66,c. Thặng dư vốn cổ phần,c.share_premium,2.717790e+08,2.717790e+08,2.717790e+08,2.717790e+08
67,d. Cổ phiếu quỹ,d.treasury_shares,NaN,NaN,NaN,NaN
68,e. Cổ phiếu ưu đãi,e.preferred_stock,NaN,NaN,NaN,NaN
69,g. Vốn khác,g.other_capital,NaN,NaN,NaN,NaN
70,2. Quỹ của TCTD,n_2.reserves,1.758306e+10,1.478957e+10,1.478957e+10,1.478957e+10
71,3. Chênh lệch tỷ giá hối đoái,n_3.foreign_exchange_differences,NaN,-3.195340e+08,-2.438160e+08,-6.536700e+07
72,4. Chênh lệch đánh giá lại tài sản,n_4.assets_revaluation_differences,NaN,NaN,NaN,NaN
73,5. Lợi nhuận chưa phân phối/Lỗ lũy kế,n_5.undistributed_earnings_after_tax_accumulat...,2.529831e+10,2.530712e+10,2.102653e+10,2.741202e+10
74,6. Lợi ích cổ đông không kiểm soát,n_6.minoritys_interest,NaN,NaN,NaN,NaN
75,IX. Lợi ích của cổ đông thiểu số,ix.minority_interest,NaN,NaN,NaN,NaN
76,TỔNG NỢ PHẢI TRẢ VÀ VỐN CHỦ SỞ HỮU,total_liabilities_and_owners_equity,1.025850e+12,9.485492e+11,9.335414e+11,8.916746e+11

In [12]:
finance.income_statement(period='quarter')

,item,item_id,2025-Q4,2025-Q3,2025-Q2,2025-Q1
0,1. Thu nhập lãi và các khoản thu nhập tương tự,n_1.interest_income_and_similar_income,1.608042e+10,1.504940e+10,1.429870e+10,1.332731e+10
1,2. Chi phí lãi và các chi phí tương tự,n_2.interest_expense_and_similar_expenses,8.987152e+09,8.279694e+09,7.614847e+09,6.968441e+09
2,I. Thu nhập lãi thuần,i.net_interest_income,7.093272e+09,6.769710e+09,6.683848e+09,6.358865e+09
3,3. Thu nhập từ hoạt động dịch vụ,n_3.fee_and_commission_income,1.381930e+09,1.317755e+09,1.102158e+09,1.394280e+09
4,4. Chi phí hoạt động dịch vụ,n_4.fee_and_commission_expenses,4.876590e+08,5.223300e+08,5.174270e+08,5.219670e+08
5,II. Lãi/lỗ thuần từ hoạt động dịch vụ,ii.net_fee_and_commission_income,8.942710e+08,7.954250e+08,5.847310e+08,8.723130e+08
6,III. Lãi/lỗ thuần từ hoạt động kinh doanh ngoạ...,iii.net_gain_loss_from_foreign_currencies_and_...,1.371410e+08,4.491500e+08,6.700050e+08,4.755900e+08
7,IV. Lãi/lỗ thuần từ mua bán chứng khoán kinh d...,iv.net_gain_loss_from_trading_securities,4.656100e+07,3.673660e+08,3.659000e+07,2.379900e+07
8,V. Lãi/lỗ thuần từ mua bán chứng khoán đầu tư,v.net_gain_loss_from_investment_securities,-4.778200e+07,-3.000000e+04,4.460910e+08,-1.495000e+06
9,5. Thu nhập từ hoạt động khác,n_5.other_income,4.101560e+08,3.706570e+08,1.163413e+09,2.844680e+08
10,6. Chi phí hoạt động khác,n_6.other_expenses,3.667140e+08,3.859200e+08,3.506900e+08,1.020830e+08
11,VI. Lãi/lỗ thuần từ hoạt động khác,vi.net_other_income,4.344200e+07,-1.526300e+07,8.127230e+08,1.823850e+08
12,"VII. Thu nhập từ góp vốn, mua cổ phần",vii.income_from_capital_contribution_and_long_...,3.914100e+07,1.830700e+07,5.855600e+07,3.171000e+06
13,VIII. Chi phí hoạt động,viii.operating_expenses,2.782374e+09,2.713933e+09,2.736160e+09,2.691892e+09
14,IX. Lợi nhuận thuần từ hoạt động kinh doanh tr...,ix.operating_profit_before_provision_for_credi...,5.423672e+09,5.670732e+09,6.556384e+09,5.222736e+09
15,X. Chi phí dự phòng rủi ro tín dụng,x.provision_for_credit_losses,1.956645e+09,2.889360e+08,4.630390e+08,6.261280e+08
16,XI. Tổng lợi nhuận trước thuế (IX-X),xi.profit_before_tax,3.467027e+09,5.381796e+09,6.093345e+09,4.596608e+09
17,7. Chi phí thuế TNDN hiện hành,n_7.current_corporate_income_tax_expenses,6.632690e+08,1.081502e+09,1.210700e+09,9.585510e+08
18,8. Chi phí thuế TNDN hoãn lại,n_8.deferred_income_tax_expenses,1.907300e+07,1.970500e+07,1.486000e+06,-4.020900e+07
19,XII. Chi phí thuế TNDN,xii.corporate_income_tax,6.823420e+08,1.101207e+09,1.212186e+09,9.183420e+08
20,XIII. Lợi nhuận sau thuế (XI-XII),xiii.net_profit_after_tax,2.784685e+09,4.280589e+09,4.881159e+09,3.678266e+09
21,XIV. Lợi ích của cổ đông thiểu số,xiv.minority_interest,NaN,NaN,NaN,NaN
22,XV. Lợi nhuận sau thuế của cổ đông của Ngân hà...,xv.net_profit_atttributable_to_the_equity_hold...,2.784685e+09,4.280589e+09,4.881159e+09,3.678266e+09
23,Lãi cơ bản trên cổ phiếu (BCTC) (VNÐ),earning_per_share_vnd,NaN,NaN,NaN,8.230000e+02