In [1]:
from vnstock import register_user
register_user()

📦 **Vnstock 3.5.0 is available**
Current version: 3.4.2
Update: `pip install vnstock --upgrade`
Release history: https://vnstocks.com/docs/tai-lieu/lich-su-phien-ban

📦 **Vnai 2.4.0 is available**
Current version: 2.3.9
Update: `pip install vnai --upgrade`
Release history: https://pypi.org/project/vnai/#history

======================================================================
  VNSTOCK - ĐĂNG KÝ API KEY
======================================================================
✓ API key: vnstock_1dfd293...
✓ Tier (Gói): free
✓ Giới hạn (Limits): {'per_minute': 60, 'per_hour': 3600}

✓ API key: vnst***3...
✓ Tier (Gói): free
✓ Giới hạn (Limits): {'per_minute': 60, 'per_hour': 3600}

True

In [2]:
import pandas as pd
# Show all rows
pd.set_option('display.max_rows', None)

In [3]:
# Import các module của vnstock
from vnstock import Listing, Quote, Company, Finance, Trading, Screener

# Cách khác: Import từ nguồn dữ liệu cụ thể
# from vnstock.explorer.vci import Listing, Quote, Company, Finance, Trading
# from vnstock.explorer.tcbs import Quote, Company, Finance, Trading, Screener

print("✅ Tất cả modules đã được import thành công!")

✅ Tất cả modules đã được import thành công!

In [4]:
# VCI là nguồn dữ liệu từ CK Vietcap bên cạnh nguồn từ TCBS
from vnstock import Listing
listing = Listing(source='KBS')

In [5]:
# Liệt kê tất cả mã chứng khoán theo nhóm phân loại. Ví dụ HOSE, VN30, VNMidCap, VNSmallCap, VNAllShare, VN100, ETF, HNX, HNX30, HNXCon, HNXFin, HNXLCap, HNXMSCap, HNXMan, UPCOM, FU_INDEX (mã chỉ số hợp đồng tương lai), CW (chứng quyền)
vn_30_list = listing.symbols_by_group('VN30')
print(vn_30_list)

0     ACB
1     BID
2     CTG
3     DGC
4     FPT
5     GAS
6     GVR
7     HDB
8     HPG
9     LPB
10    MBB
11    MSN
12    MWG
13    PLX
14    SAB
15    SHB
16    SSB
17    SSI
18    STB
19    TCB
20    TPB
21    VCB
22    VHM
23    VIB
24    VIC
25    VJC
26    VNM
27    VPB
28    VPL
29    VRE
Name: symbol, dtype: str

In [6]:
finance = Finance(symbol='ACB', source='VCI', period='quarter')
df = finance.balance_sheet()
df_5_years = df.head(20)

In [7]:
import pandas as pd

# Hiển thị tất cả các cột
pd.set_option('display.max_columns', None)
# (Tùy chọn) Hiển thị tất cả các dòng nếu bạn muốn xem toàn bộ
pd.set_option('display.max_rows', None)
# (Tùy chọn) Hiển thị nội dung văn bản bên trong ô lớn hơn (tránh bị cắt chữ)
pd.set_option('display.max_colwidth', None)

df_5_years

,ticker,yearReport,lengthReport,TOTAL ASSETS (Bn. VND),Cash and cash equivalents (Bn. VND),Balances with the SBV,Placements with and loans to other credit institutions,"Trading Securities, net",Trading Securities,Provision for diminution in value of Trading Securities,Derivatives and other financial liabilities,"Loans and advances to customers, net",Loans and advances to customers,Less: Provision for losses on loans and advances to customers,Investment Securities,Available-for Sales Securities,Held-to-Maturity Securities,Less: Provision for diminution in value of investment securities,Long-term investments (Bn. VND),Investments in associate companies,Other long-term assets (Bn. VND),Less: Provision for diminuation in value of long term investments,Fixed assets (Bn. VND),Tangible fixed assets,Intagible fixed assets,Investment in properties,Other Assets,TOTAL RESOURCES (Bn. VND),LIABILITIES (Bn. VND),Due to Gov and borrowings from SBV,Deposits and borrowings from other credit institutions,Deposits from customers,_Derivatives and other financial liabilities,"Funds received from Gov, international and other institutions",Convertible bonds/CDs and other valuable papers issued,Other liabilities,OWNER'S EQUITY(Bn.VND),Capital,Reserves,Foreign Currency Difference reserve,Undistributed earnings (Bn. VND),Paid-in capital (Bn. VND),MINORITY INTERESTS
0,ACB,2025,4,1025850127000000,8624548000000,16574958000000,149990681000000,6544882000000,6708358000000,-163476000000,324298000000,679152623000000,686777352000000,-7624729000000,144164116000000,132778839000000,11396527000000,-11250000000,74699000000,0,233739000000,-159040000000,5438550000000,3200487000000,2238063000000,149673000000,14811099000000,1025850127000000,931330408000000,32976139000000,154999539000000,585180175000000,0,19079000000,133294422000000,24861054000000,94519719000000,51638345000000,17583061000000,0,25298313000000,51366566000000,0
1,ACB,2025,3,948549176000000,6785568000000,15197467000000,104925948000000,5918486000000,6072639000000,-154153000000,0,663032417000000,669188125000000,-6155708000000,133759576000000,121853383000000,11906193000000,0,126774000000,0,292867000000,-166093000000,5400704000000,3209383000000,2191321000000,103544000000,13298692000000,948549176000000,857133676000000,20691569000000,129176089000000,571028953000000,123668000000,22456000000,113387071000000,22703870000000,91415500000000,51638345000000,14789568000000,-319534000000,25307121000000,51366566000000,0
2,ACB,2025,2,933541420000000,6666091000000,5439937000000,125447269000000,4958406000000,5160049000000,-201643000000,0,627669396000000,633748683000000,-6079287000000,145778688000000,133862829000000,11915859000000,0,124885000000,0,292867000000,-167982000000,5396553000000,3223395000000,2173158000000,62310000000,11997885000000,933541420000000,846330791000000,21026778000000,96259274000000,567406860000000,318849000000,24547000000,139552843000000,21741640000000,87210629000000,51638345000000,14789568000000,-243816000000,21026532000000,51366566000000,0
3,ACB,2025,1,891674563000000,5857654000000,13457514000000,129347480000000,4307534000000,4479661000000,-172127000000,0,592430761000000,598805866000000,-6375105000000,129978304000000,118052779000000,11925525000000,0,126773000000,0,292867000000,-166094000000,5311943000000,3148991000000,2162952000000,177005000000,10679595000000,891674563000000,804599986000000,18643287000000,101284086000000,550375020000000,171338000000,26725000000,114051801000000,20047729000000,87074577000000,44938358000000,14789568000000,-65367000000,27412018000000,44666579000000,0
4,ACB,2024,4,864005703000000,5696449000000,25219753000000,117882259000000,3881151000000,4029088000000,-147937000000,55992000000,573946692000000,580686248000000,-6739556000000,121090243000000,108918477000000,12171766000000,0,124935000000,0,292867000000,-167932000000,5412370000000,3222198000000,2190172000000,177005000000,10518854000000,864005703000000,780544025000000,7954853000000,111591668000000,537304578000000,0,28008000000,101650446000000,22014472000000,83461678000000,44938358000000,14789568000000,0,23733752000000,44666579000000,0
5,ACB,2024,3,777392922000000,5870526000000,8392393000000,92090423000000,6965867000000,7059448000000,-93581000000,267873000000,548247424000000,554908474000000,-6661050000000,100862391000000,88938255000000,11931400000000,-7264000000,127425000000,0,292867000000,-165442000000,4642986000000,3084190000000,1558796000000,177005000000,9748609000000,777392922000000,698538661000000,19152000000,73519652000000,512123668000000,0,31641000000,90366104000000,22478444000000,78854261000000,44938358000000,11557435000000,-62053000000,22420521000000,44666579000000,0
6,ACB,2024,2,769678700000000,6594138000000,15724945000000,105419092000000,6125105000000,6236053000000,-110948000000,0,543853038000000,550172293000000,-6319255000000,77089507000000,61663820000000,15438107000000,-12420000000,128875000000,0,292867000000,-163992000000,4665559000000,3119424000000,1546135000000,177005000000,9901436000000,769678700000000,694886022000000,15945000000,93760618000000,511695775000000,61832000000,33175000000,66953215000000,22365462000000,74792678000000,44938358000000,11557435000000,-253241000000,18550126000000,44666579000000,0
7,ACB,2024,1,727297968000000,6470319000000,7851936000000,121950918000000,7377873000000,7469189000000,-91316000000,0,500339694000000,506112216000000,-5772522000000,67999640000000,45959043000000,22040597000000,0,140025000000,0,303387000000,-163362000000,4670671000000,3234051000000,1436620000000,177005000000,10319887000000,727297968000000,652507236000000,66583000000,89358866000000,492804396000000,518306000000,37321000000,49011681000000,20710083000000,74790732000000,39112283000000,11557435000000,-70648000000,24191662000000,38840504000000,0
8,ACB,2023,4,718794589000000,6909300000000,18504814000000,114873931000000,7177069000000,7323489000000,-146420000000,0,482234900000000,487601852000000,-5366952000000,73463347000000,44903768000000,28559579000000,0,140025000000,0,303387000000,-163362000000,4762561000000,3317568000000,1444993000000,177005000000,10551637000000,718794589000000,647838628000000,88000000,89506662000000,482702731000000,117126000000,41534000000,52410014000000,23060473000000,70955961000000,39112283000000,11557435000000,0,20286243000000,38840504000000,0
9,ACB,2023,3,648509938000000,6552560000000,12405261000000,98170290000000,1892458000000,2023422000000,-130964000000,79210000000,444641463000000,449751645000000,-5110182000000,70233160000000,34885148000000,35348012000000,0,140025000000,0,303387000000,-163362000000,4447517000000,3131419000000,1316098000000,177005000000,9770989000000,648509938000000,581684649000000,18552000000,64119526000000,445499845000000,0,45249000000,48858665000000,23142812000000,66825289000000,39112283000000,9220106000000,-124393000000,18617293000000,38840504000000,0
10,ACB,2023,2,630893170000000,5983591000000,11514014000000,89763275000000,1068921000000,1182088000000,-113167000000,114028000000,429058305000000,434031946000000,-4973641000000,79112752000000,42472830000000,36639922000000,0,146321000000,0,303387000000,-157066000000,4292448000000,3101005000000,1191443000000,177005000000,9662510000000,630893170000000,568025989000000,2921000000,68957498000000,432410465000000,0,49182000000,44657505000000,21948418000000,62867181000000,39112283000000,9220106000000,-44922000000,14579714000000,38840504000000,0
11,ACB,2023,1,611223523000000,6654779000000,6429413000000,94638910000000,1541928000000,1699679000000,-157751000000,395042000000,406620881000000,411288535000000,-4667654000000,79206253000000,36077453000000,43128800000000,0,141148000000,0,303387000000,-162239000000,4127353000000,2966929000000,1160424000000,177005000000,11290811000000,611223523000000,548693358000000,6110000000,52857299000000,422755092000000,0,55580000000,50155919000000,22863358000000,62530165000000,34046130000000,9220106000000,-43527000000,19307456000000,33774351000000,0
12,ACB,2022,4,607875185000000,8460892000000,13657531000000,85971313000000,1131327000000,1320941000000,-189614000000,100072000000,408856508000000,413706244000000,-4849736000000,75534794000000,31854915000000,43679879000000,0,146814000000,0,303387000000,-156573000000,3981376000000,2849732000000,1131644000000,177005000000,9857553000000,607875185000000,549436522000000,505876000000,67840840000000,413952789000000,0,60188000000,44304367000000,22772462000000,58438663000000,34046130000000,9220125000000,0,15172408000000,33774351000000,0
13,ACB,2022,3,561113724000000,6820742000000,7285530000000,62584455000000,1438382000000,1641739000000,-203357000000,67174000000,396661986000000,402250931000000,-5588945000000,71265935000000,27533790000000,43732145000000,0,154549000000,0,309337000000,-154788000000,3733847000000,2665262000000,1068585000000,177005000000,10924119000000,561113724000000,505378993000000,34000000,51830484000000,392023517000000,0,64550000000,40052881000000,21407527000000,55734731000000,34046130000000,7164297000000,166147000000,14358157000000,33774351000000,0
14,ACB,2022,2,543736728000000,7179996000000,11267755000000,57122539000000,1481310000000,1683277000000,-201967000000,91556000000,390049375000000,395598651000000,-5549276000000,64489044000000,18577997000000,45917151000000,-6104000000,158000000000,0,309337000000,-151337000000,3625120000000,2601457000000,1023663000000,216027000000,8056006000000,543736728000000,491670697000000,565000000,50712628000000,388131932000000,0,70779000000,34851291000000,17903502000000,52066031000000,27291260000000,7164297000000,84439000000,17526035000000,27019481000000,0
15,ACB,2022,1,528636428000000,6281931000000,18208130000000,54337806000000,5068428000000,5159447000000,-91019000000,92408000000,374124636000000,379982950000000,-5858314000000,58710197000000,10634517000000,48079089000000,-3409000000,207771000000,0,309837000000,-102066000000,3678381000000,2641814000000,1036567000000,216027000000,7710713000000,528636428000000,480433095000000,0,44323457000000,386050921000000,0,79176000000,30949666000000,19029875000000,48203333000000,27291260000000,7164297000000,14889000000,13732887000000,27019481000000,0
16,ACB,2021,4,527769944000000,7509877000000,32349574000000,49818776000000,11259731000000,11325371000000,-65640000000,226545000000,356050950000000,361912538000000,-5861588000000,59474604000000,9739539000000,49743071000000,-8006000000,171925000000,0,299317000000,-127392000000,3762548000000,2685070000000,1077478000000,216027000000,6929387000000,527769944000000,482869035000000,0,54393939000000,379920669000000,0,86066000000,30547883000000,17920478000000,44900909000000,27291260000000,7164297000000,0,10445352000000,27019481000000,0
17,ACB,2021,3,479308753000000,7010081000000,33532941000000,28675646000000,10151989000000,10239936000000,-87947000000,63982000000,330911258000000,336491602000000,-5580344000000,58533725000000,8886513000000,49807650000000,-160438000000,88068000000,2967000000,101827000000,-16726000000,3646321000000,2581210000000,1065111000000,216027000000,6478715000000,479308753000000,436825317000000,0,20324174000000,365770473000000,0,93799000000,32469936000000,18166935000000,42483436000000,27291260000000,5742084000000,11022000000,9439070000000,27019481000000,0
18,ACB,2021,2,471275438000000,6870892000000,21912320000000,28988545000000,10270741000000,10375295000000,-104554000000,82038000000,336827639000000,341667500000000,-4839861000000,55528394000000,9535454000000,46253125000000,-260185000000,87912000000,2967000000,101827000000,-16882000000,3703279000000,2628026000000,1075253000000,216027000000,6787651000000,471275438000000,430895193000000,0,27085956000000,358474148000000,0,100653000000,27455319000000,17779117000000,40380245000000,21887364000000,5742084000000,10446000000,12740351000000,21615585000000,0
19,ACB,2021,1,449514732000000,6037588000000,20232572000000,27746394000000,4419502000000,4529892000000,-110390000000,135503000000,320754992000000,324311117000000,-3556125000000,58893891000000,10294062000000,48932832000000,-333003000000,99549000000,2967000000,101827000000,-5245000000,3720662000000,2664580000000,1056082000000,216027000000,7258052000000,449514732000000,411585397000000,0,20335604000000,352217653000000,0,108249000000,20384044000000,18539847000000,37929335000000,21887364000000,5742084000000,-2229000000,10302116000000,21615585000000,0

In [8]:
df = finance.income_statement()
df_5_years = df.head(20)

In [9]:
df_5_years

,ticker,yearReport,lengthReport,Revenue (Bn. VND),Revenue YoY (%),Attribute to parent company (Bn. VND),Attribute to parent company YoY (%),Interest and Similar Income,Interest and Similar Expenses,Net Interest Income,Fees and Comission Income,Fees and Comission Expenses,Net Fee and Commission Income,Net gain (loss) from foreign currency and gold dealings,Net gain (loss) from trading of trading securities,Net gain (loss) from disposal of investment securities,Net Other income/(expenses),Other expenses,Net Other income/expenses,Dividends received,Total operating revenue,General & Admin Expenses,Operating Profit before Provision,Provision for credit losses,Profit before tax,Tax For the Year,Business income tax - current,Business income tax - deferred,Net Profit For the Year,Attributable to parent company,EPS_basis
0,ACB,2025,4,16080424000000,0.189523,2784685000000,-0.387357,16080424000000,-8987152000000,7093272000000,1381930000000,-487659000000,894271000000,137141000000,46561000000,-47782000000,410156000000,-366714000000,43442000000,39141000000,8206046000000,-2782374000000,5423672000000,-1956645000000,3467027000000,-682342000000,-663269000000,-19073000000,2784685000000,2784685000000,542
1,ACB,2025,3,15049404000000,0.164628,4280589000000,0.105982,15049404000000,-8279694000000,6769710000000,1317755000000,-522330000000,795425000000,449150000000,367366000000,-30000000,370657000000,-385920000000,-15263000000,18307000000,8384665000000,-2713933000000,5670732000000,-288936000000,5381796000000,-1101207000000,-1081502000000,-19705000000,4280589000000,4280589000000,0
2,ACB,2025,2,14298695000000,0.146214,4881159000000,0.092326,14298695000000,-7614847000000,6683848000000,1102158000000,-517427000000,584731000000,670005000000,36590000000,446091000000,1163413000000,-350690000000,812723000000,58556000000,9292544000000,-2736160000000,6556384000000,-463039000000,6093345000000,-1212186000000,-1210700000000,-1486000000,4881159000000,4881159000000,0
3,ACB,2025,1,13327306000000,0.111758,3678266000000,-0.058164,13327306000000,-6968441000000,6358865000000,1394280000000,-521967000000,872313000000,475590000000,23799000000,-1495000000,284468000000,-102083000000,182385000000,3171000000,7914628000000,-2691892000000,5222736000000,-626128000000,4596608000000,-918342000000,-958551000000,40209000000,3678266000000,3678266000000,0
4,ACB,2024,4,13518376000000,0.080173,4545364000000,0.134560,13518376000000,-6438085000000,7080291000000,1435715000000,-566890000000,868825000000,344167000000,-26090000000,213050000000,419472000000,-346882000000,72590000000,5463000000,8558296000000,-2739350000000,5818946000000,-147675000000,5671271000000,-1125907000000,-1086127000000,-39780000000,4545364000000,4545364000000,1017
5,ACB,2024,3,12922067000000,-0.007819,3870395000000,-0.041407,12922067000000,-6040680000000,6881387000000,1325822000000,-578633000000,747189000000,166635000000,71287000000,47199000000,259065000000,-56305000000,202760000000,19544000000,8136001000000,-2933714000000,5202287000000,-358243000000,4844044000000,-973649000000,-971306000000,-2343000000,3870395000000,3870395000000,0
6,ACB,2024,2,12474712000000,-0.081634,4468590000000,0.155915,12474712000000,-5363206000000,7111506000000,1421150000000,-543581000000,877569000000,426650000000,-41231000000,-14005000000,415272000000,-129401000000,285871000000,5651000000,8652011000000,-2465618000000,6186393000000,-588150000000,5598243000000,-1129653000000,-1075344000000,-54309000000,4468590000000,4468590000000,779
7,ACB,2024,1,11987594000000,-0.093516,3905419000000,-0.055528,11987594000000,-5266076000000,6721518000000,1282271000000,-537069000000,745202000000,233300000000,196391000000,204068000000,172323000000,-109907000000,62416000000,5556000000,8168451000000,-2763921000000,5404530000000,-512217000000,4892313000000,-986894000000,-1066922000000,80028000000,3905419000000,3905419000000,1006
8,ACB,2023,4,12515015000000,0.051202,4006279000000,0.395664,12515015000000,-6225399000000,6289616000000,1305933000000,-578635000000,727298000000,28950000000,-13925000000,1358428000000,216906000000,-230699000000,-13793000000,1889000000,8378463000000,-3013248000000,5365215000000,-321641000000,5043574000000,-1037295000000,-975257000000,-62038000000,4006279000000,4006279000000,1031
9,ACB,2023,3,13023905000000,0.262001,4037579000000,0.125617,13023905000000,-6814777000000,6209128000000,1301774000000,-538187000000,763587000000,315762000000,67760000000,881942000000,202751000000,-55714000000,147037000000,39166000000,8424382000000,-2868218000000,5556164000000,-520683000000,5035481000000,-997902000000,-996856000000,-1046000000,4037579000000,4037579000000,1040
10,ACB,2023,2,13583597000000,0.442070,3865846000000,-0.019604,13583597000000,-7337925000000,6245672000000,1262569000000,-458183000000,804386000000,327437000000,71566000000,407802000000,200858000000,-37975000000,162883000000,3774000000,8023520000000,-2485180000000,5538340000000,-705893000000,4832447000000,-966601000000,-911557000000,-55044000000,3865846000000,3865846000000,797
11,ACB,2023,1,13224279000000,0.460626,4135029000000,0.257790,13224279000000,-7009125000000,6215154000000,1075475000000,-448409000000,627066000000,437956000000,42982000000,-1032000000,576702000000,-9458000000,567244000000,30781000000,7920151000000,-2507640000000,5412511000000,-256014000000,5156497000000,-1021468000000,-1109352000000,87884000000,4135029000000,4135029000000,1224
12,ACB,2022,4,11905432000000,0.408088,2870518000000,0.182015,11905432000000,-5451215000000,6454217000000,1392840000000,-465807000000,927033000000,503889000000,-110032000000,-2708000000,163883000000,-23306000000,140577000000,13020000000,7925996000000,-4064328000000,3861668000000,-250585000000,3611083000000,-740565000000,-692817000000,-47748000000,2870518000000,2870518000000,849
13,ACB,2022,3,10320044000000,0.244802,3586992000000,0.705967,10320044000000,-4287794000000,6032250000000,1296877000000,-430092000000,866785000000,95844000000,-39964000000,-1502000000,104791000000,19046000000,123837000000,13711000000,7090961000000,-2525765000000,4565196000000,-90436000000,4474760000000,-887768000000,-866236000000,-21532000000,3586992000000,3586992000000,1063
14,ACB,2022,2,9419513000000,0.088537,3943148000000,0.523489,9419513000000,-3813123000000,5606390000000,1342948000000,-349681000000,993267000000,145269000000,-226653000000,18353000000,412721000000,-56632000000,356089000000,30632000000,6923347000000,-2276351000000,4646996000000,267364000000,4914360000000,-971212000000,-903936000000,-67276000000,3943148000000,3943148000000,879
15,ACB,2022,1,9053845000000,0.088871,3287535000000,0.323804,9053845000000,-3613173000000,5440672000000,1024894000000,-285735000000,739159000000,303367000000,-11224000000,6505000000,429099000000,-59908000000,369191000000,2093000000,6849763000000,-2738601000000,4111162000000,2843000000,4114005000000,-826470000000,-982622000000,156152000000,3287535000000,3287535000000,1217
16,ACB,2021,4,8455034000000,-0.000777,2428495000000,-0.047478,8455034000000,-3660712000000,4794322000000,1062911000000,-316093000000,746818000000,237959000000,61319000000,58365000000,134023000000,-64922000000,69101000000,3337000000,5971221000000,-2417444000000,3553777000000,-524017000000,3029760000000,-601265000000,-528304000000,-72961000000,2428495000000,2428495000000,898
17,ACB,2021,3,8290513000000,0.045349,2102615000000,0.013517,8290513000000,-3770002000000,4520511000000,897088000000,-261529000000,635559000000,205933000000,183481000000,92038000000,148382000000,-106055000000,42327000000,10333000000,5690182000000,-2254497000000,3435685000000,-820086000000,2615599000000,-512984000000,-558745000000,45761000000,2102615000000,2102615000000,323
18,ACB,2021,2,8653369000000,0.136707,2588235000000,0.700934,8653369000000,-3662982000000,4990387000000,1186356000000,-299977000000,886379000000,231524000000,91668000000,44709000000,174708000000,-195620000000,-20912000000,3462000000,6227217000000,-1592538000000,4634679000000,-1386245000000,3248434000000,-660199000000,-591994000000,-68205000000,2588235000000,2588235000000,673
19,ACB,2021,1,8314894000000,0.059140,2483401000000,0.615690,8314894000000,-3675322000000,4639572000000,880105000000,-254898000000,625207000000,196140000000,113492000000,48939000000,246046000000,-197099000000,48947000000,3080000000,5675377000000,-1965297000000,3710080000000,-605761000000,3104319000000,-620918000000,-710036000000,89118000000,2483401000000,2483401000000,1149