In [1]:
from vnstock import register_user
register_user()

📦 **Vnstock 3.5.0 is available**
Current version: 3.4.2
Update: `pip install vnstock --upgrade`
Release history: https://vnstocks.com/docs/tai-lieu/lich-su-phien-ban

📦 **Vnai 2.4.0 is available**
Current version: 2.3.9
Update: `pip install vnai --upgrade`
Release history: https://pypi.org/project/vnai/#history

======================================================================
  VNSTOCK - ĐĂNG KÝ API KEY
======================================================================
✓ API key: vnstock_1dfd293...
✓ Tier (Gói): free
✓ Giới hạn (Limits): {'per_minute': 60, 'per_hour': 3600}

✓ API key: vnst***3...
✓ Tier (Gói): free
✓ Giới hạn (Limits): {'per_minute': 60, 'per_hour': 3600}

True

In [2]:
import pandas as pd

# Thiết lập hiển thị tối đa số dòng (không giới hạn)
pd.set_option('display.max_rows', None)

# Nếu bạn muốn hiển thị full cột khi in DataFrame:
pd.set_option('display.max_columns', None)

In [ ]:
from src.data.data_fetcher import DataFetcher

fetch_agent = DataFetcher(source='VCI')

vn30_tickers = fetch_agent.get_group_ticker("VN30")
print(vn30_tickers)

0     ACB
1     BID
2     CTG
3     DGC
4     FPT
5     GAS
6     GVR
7     HDB
8     HPG
9     LPB
10    MBB
11    MSN
12    MWG
13    PLX
14    SAB
15    SHB
16    SSB
17    SSI
18    STB
19    TCB
20    TPB
21    VCB
22    VHM
23    VIB
24    VIC
25    VJC
26    VNM
27    VPB
28    VPL
29    VRE
Name: symbol, dtype: str

In [ ]:
master_df = fetch_agent.get_merged_financial_reports(vn30_tickers)
# Kiểm tra xem tổng quan bảng (Dự kiến 30 mã * 20 quý = 600 dòng)
master_df.info()

In [4]:
master_df = pd.read_csv("raw_fundermental_data.csv")

In [6]:
df_with_price = fetch_agent.align_and_fetch_price(master_df, align_quarter_dates=True)

# Chạy tính Return cho FinRL
df_finrl = fetch_agent.calculate_y_return(df_with_price)

# In ra xem 
df_finrl[['ticker', 'yearReport', 'lengthReport', 'Quarter_Time', 'actual_price_date', 'adj_close_q', 'y_return']]

Đang fetch giá ACB từ 2021-05-27 đến 2026-04-16...
Đang fetch giá BID từ 2021-05-27 đến 2026-04-16...
Đang fetch giá CTG từ 2021-05-27 đến 2026-04-16...
Đang fetch giá DGC từ 2021-05-27 đến 2026-04-16...
Đang fetch giá FPT từ 2021-05-27 đến 2026-04-16...
Đang fetch giá GAS từ 2021-05-27 đến 2026-04-16...
Đang fetch giá GVR từ 2021-05-27 đến 2026-04-16...
Đang fetch giá HDB từ 2021-05-27 đến 2026-04-16...
Đang fetch giá HPG từ 2021-05-27 đến 2026-04-16...
Đang fetch giá LPB từ 2021-05-27 đến 2026-04-16...
Đang fetch giá MBB từ 2021-05-27 đến 2026-04-16...
Đang fetch giá MSN từ 2021-05-27 đến 2026-04-16...
Đang fetch giá MWG từ 2021-05-27 đến 2026-04-16...
Đang fetch giá PLX từ 2021-05-27 đến 2026-04-16...
Đang fetch giá SAB từ 2021-05-27 đến 2026-04-16...
Đang fetch giá SHB từ 2021-05-27 đến 2026-04-16...
Đang fetch giá SSB từ 2021-05-27 đến 2026-04-16...
Đang fetch giá SSI từ 2021-05-27 đến 2026-04-16...
Đang fetch giá STB từ 2021-05-27 đến 2026-04-16...
Đang fetch giá TCB từ 2021-05-27 đến 2026-04-16...
Đang fetch giá TPB từ 2021-05-27 đến 2026-04-16...
Đang fetch giá VCB từ 2021-05-27 đến 2026-04-16...
Đang fetch giá VHM từ 2021-05-27 đến 2026-04-16...
Đang fetch giá VIB từ 2021-05-27 đến 2026-04-16...
Đang fetch giá VIC từ 2021-05-27 đến 2026-04-16...
Đang fetch giá VJC từ 2021-05-27 đến 2026-04-16...
Đang fetch giá VNM từ 2021-05-27 đến 2026-04-16...
Đang fetch giá VPB từ 2021-05-27 đến 2026-04-16...
Đang fetch giá VPL từ 2008-08-27 đến 2026-04-16...
Đang fetch giá VRE từ 2021-05-27 đến 2026-04-16...

,ticker,yearReport,lengthReport,Quarter_Time,actual_price_date,adj_close_q,y_return
0,ACB,2021,1,2021-03-31,2021-06-01,15.80,-0.051293
1,ACB,2021,2,2021-06-30,2021-09-01,15.01,0.045581
2,ACB,2021,3,2021-09-30,2021-12-01,15.71,-0.003188
3,ACB,2021,4,2021-12-31,2022-04-01,15.66,-0.070773
4,ACB,2022,1,2022-03-31,2022-06-01,14.59,-0.015890
5,ACB,2022,2,2022-06-30,2022-09-05,14.36,-0.084988
6,ACB,2022,3,2022-09-30,2022-12-01,13.19,0.115168
7,ACB,2022,4,2022-12-31,2023-04-03,14.80,0.014755
8,ACB,2023,1,2023-03-31,2023-06-01,15.02,0.061329
9,ACB,2023,2,2023-06-30,2023-09-05,15.97,-0.036344
10,ACB,2023,3,2023-09-30,2023-12-01,15.40,0.259864
11,ACB,2023,4,2023-12-31,2024-04-01,19.97,0.036868
12,ACB,2024,1,2024-03-31,2024-06-03,20.72,-0.005808
13,ACB,2024,2,2024-06-30,2024-09-04,20.60,0.019707
14,ACB,2024,3,2024-09-30,2024-12-02,21.01,0.035075
15,ACB,2024,4,2024-12-31,2025-04-01,21.76,-0.030800
16,ACB,2025,1,2025-03-31,2025-06-02,21.10,0.264913
17,ACB,2025,2,2025-06-30,2025-09-03,27.50,-0.136132
18,ACB,2025,3,2025-09-30,2025-12-01,24.00,NaN
19,ACB,2025,4,2025-12-31,NaT,NaN,NaN
20,BID,2021,1,2021-03-31,2021-06-01,27.55,-0.207388
21,BID,2021,2,2021-06-30,2021-09-01,22.39,0.127315
22,BID,2021,3,2021-09-30,2021-12-01,25.43,0.235105
23,BID,2021,4,2021-12-31,2022-04-01,32.17,-0.232748
24,BID,2022,1,2022-03-31,2022-06-01,25.49,0.116867
25,BID,2022,2,2022-06-30,2022-09-05,28.65,-0.012645
26,BID,2022,3,2022-09-30,2022-12-01,28.29,0.162749
27,BID,2022,4,2022-12-31,2023-04-03,33.29,-0.044534
28,BID,2023,1,2023-03-31,2023-06-01,31.84,0.078786
29,BID,2023,2,2023-06-30,2023-09-05,34.45,-0.067543
30,BID,2023,3,2023-09-30,2023-12-01,32.20,0.279418
31,BID,2023,4,2023-12-31,2024-04-01,42.58,-0.096579
32,BID,2024,1,2024-03-31,2024-06-03,38.66,0.034324
33,BID,2024,2,2024-06-30,2024-09-04,40.01,-0.051543
34,BID,2024,3,2024-09-30,2024-12-02,38.00,0.014889
35,BID,2024,4,2024-12-31,2025-04-01,38.57,-0.088309
36,BID,2025,1,2025-03-31,2025-06-02,35.31,0.197499
37,BID,2025,2,2025-06-30,2025-09-03,43.02,-0.152099
38,BID,2025,3,2025-09-30,2025-12-01,36.95,NaN
39,BID,2025,4,2025-12-31,NaT,NaN,NaN
40,CTG,2021,1,2021-03-31,2021-06-01,24.42,-0.240492
41,CTG,2021,2,2021-06-30,2021-09-01,19.20,0.059153
42,CTG,2021,3,2021-09-30,2021-12-01,20.37,-0.003935
43,CTG,2021,4,2021-12-31,2022-04-01,20.29,-0.175152
44,CTG,2022,1,2022-03-31,2022-06-01,17.03,0.007605
45,CTG,2022,2,2022-06-30,2022-09-05,17.16,-0.066872
46,CTG,2022,3,2022-09-30,2022-12-01,16.05,0.135554
47,CTG,2022,4,2022-12-31,2023-04-03,18.38,-0.068682
48,CTG,2023,1,2023-03-31,2023-06-01,17.16,0.155149
49,CTG,2023,2,2023-06-30,2023-09-05,20.04,-0.105139
50,CTG,2023,3,2023-09-30,2023-12-01,18.04,0.285879
51,CTG,2023,4,2023-12-31,2024-04-01,24.01,-0.071197
52,CTG,2024,1,2024-03-31,2024-06-03,22.36,0.079492
53,CTG,2024,2,2024-06-30,2024-09-04,24.21,0.015574
54,CTG,2024,3,2024-09-30,2024-12-02,24.59,0.154557
55,CTG,2024,4,2024-12-31,2025-04-01,28.70,-0.085808
56,CTG,2025,1,2025-03-31,2025-06-02,26.34,0.275651
57,CTG,2025,2,2025-06-30,2025-09-03,34.70,-0.036389
58,CTG,2025,3,2025-09-30,2025-12-01,33.46,NaN
59,CTG,2025,4,2025-12-31,NaT,NaN,NaN
60,DGC,2021,1,2021-03-31,2021-06-01,27.53,0.501337
61,DGC,2021,2,2021-06-30,2021-09-01,45.45,0.329691
62,DGC,2021,3,2021-09-30,2021-12-01,63.20,0.341883
63,DGC,2021,4,2021-12-31,2022-04-01,88.96,0.007838
64,DGC,2022,1,2022-03-31,2022-06-01,89.66,-0.044355
65,DGC,2022,2,2022-06-30,2022-09-05,85.77,-0.557607
66,DGC,2022,3,2022-09-30,2022-12-01,49.11,-0.064118
67,DGC,2022,4,2022-12-31,2023-04-03,46.06,0.067979
68,DGC,2023,1,2023-03-31,2023-06-01,49.30,0.510744
69,DGC,2023,2,2023-06-30,2023-09-05,82.16,0.044049
70,DGC,2023,3,2023-09-30,2023-12-01,85.86,0.267654
71,DGC,2023,4,2023-12-31,2024-04-01,112.21,0.041460
72,DGC,2024,1,2024-03-31,2024-06-03,116.96,-0.084806
73,DGC,2024,2,2024-06-30,2024-09-04,107.45,-0.021162
74,DGC,2024,3,2024-09-30,2024-12-02,105.20,-0.111612
75,DGC,2024,4,2024-12-31,2025-04-01,94.09,-0.097257
76,DGC,2025,1,2025-03-31,2025-06-02,85.37,0.091074
77,DGC,2025,2,2025-06-30,2025-09-03,93.51,-0.026989
78,DGC,2025,3,2025-09-30,2025-12-01,91.02,NaN
79,DGC,2025,4,2025-12-31,NaT,NaN,NaN
80,FPT,2021,1,2021-03-31,2021-06-01,43.75,0.069526
81,FPT,2021,2,2021-06-30,2021-09-01,46.90,0.060800
82,FPT,2021,3,2021-09-30,2021-12-01,49.84,0.122587
83,FPT,2021,4,2021-12-31,2022-04-01,56.34,0.007251
84,FPT,2022,1,2022-03-31,2022-06-01,56.75,-0.057107
85,FPT,2022,2,2022-06-30,2022-09-05,53.60,-0.143173
86,FPT,2022,3,2022-09-30,2022-12-01,46.45,0.079629
87,FPT,2022,4,2022-12-31,2023-04-03,50.30,0.031699
88,FPT,2023,1,2023-03-31,2023-06-01,51.92,0.310720
89,FPT,2023,2,2023-06-30,2023-09-05,70.84,-0.046520
90,FPT,2023,3,2023-09-30,2023-12-01,67.62,0.234379
91,FPT,2023,4,2023-12-31,2024-04-01,85.48,0.158786
92,FPT,2024,1,2024-03-31,2024-06-03,100.19,0.117750
93,FPT,2024,2,2024-06-30,2024-09-04,112.71,0.073778
94,FPT,2024,3,2024-09-30,2024-12-02,121.34,-0.165519
95,FPT,2024,4,2024-12-31,2025-04-01,102.83,-0.037250
96,FPT,2025,1,2025-03-31,2025-06-02,99.07,0.030518
97,FPT,2025,2,2025-06-30,2025-09-03,102.14,-0.055766
98,FPT,2025,3,2025-09-30,2025-12-01,96.60,NaN
99,FPT,2025,4,2025-12-31,NaT,NaN,NaN
100,GAS,2021,1,2021-03-31,2021-06-01,54.41,0.088083
101,GAS,2021,2,2021-06-30,2021-09-01,59.42,0.105933
102,GAS,2021,3,2021-09-30,2021-12-01,66.06,0.107674
103,GAS,2021,4,2021-12-31,2022-04-01,73.57,0.098062
104,GAS,2022,1,2022-03-31,2022-06-01,81.15,-0.011900
105,GAS,2022,2,2022-06-30,2022-09-05,80.19,-0.088884
106,GAS,2022,3,2022-09-30,2022-12-01,73.37,-0.038343
107,GAS,2022,4,2022-12-31,2023-04-03,70.61,-0.108023
108,GAS,2023,1,2023-03-31,2023-06-01,63.38,0.114798
109,GAS,2023,2,2023-06-30,2023-09-05,71.09,-0.065843
110,GAS,2023,3,2023-09-30,2023-12-01,66.56,0.036582
111,GAS,2023,4,2023-12-31,2024-04-01,69.04,-0.002465
112,GAS,2024,1,2024-03-31,2024-06-03,68.87,0.042638
113,GAS,2024,2,2024-06-30,2024-09-04,71.87,-0.098320
114,GAS,2024,3,2024-09-30,2024-12-02,65.14,-0.024869
115,GAS,2024,4,2024-12-31,2025-04-01,63.54,-0.030034
116,GAS,2025,1,2025-03-31,2025-06-02,61.66,0.034118
117,GAS,2025,2,2025-06-30,2025-09-03,63.80,0.024769
118,GAS,2025,3,2025-09-30,2025-12-01,65.40,NaN
119,GAS,2025,4,2025-12-31,NaT,NaN,NaN
120,GVR,2021,1,2021-03-31,2021-06-01,26.08,0.346501
121,GVR,2021,2,2021-06-30,2021-09-01,36.88,-0.024428
122,GVR,2021,3,2021-09-30,2021-12-01,35.99,-0.108484
123,GVR,2021,4,2021-12-31,2022-04-01,32.29,-0.317332
124,GVR,2022,1,2022-03-31,2022-06-01,23.51,0.040839
125,GVR,2022,2,2022-06-30,2022-09-05,24.49,-0.545023
126,GVR,2022,3,2022-09-30,2022-12-01,14.20,0.075264
127,GVR,2022,4,2022-12-31,2023-04-03,15.31,0.164085
128,GVR,2023,1,2023-03-31,2023-06-01,18.04,0.157155
129,GVR,2023,2,2023-06-30,2023-09-05,21.11,-0.070144
130,GVR,2023,3,2023-09-30,2023-12-01,19.68,0.492053
131,GVR,2023,4,2023-12-31,2024-04-01,32.19,0.060277
132,GVR,2024,1,2024-03-31,2024-06-03,34.19,-0.008518
133,GVR,2024,2,2024-06-30,2024-09-04,33.90,-0.089105
134,GVR,2024,3,2024-09-30,2024-12-02,31.01,0.012498
135,GVR,2024,4,2024-12-31,2025-04-01,31.40,-0.083312
136,GVR,2025,1,2025-03-31,2025-06-02,28.89,0.000000
137,GVR,2025,2,2025-06-30,2025-09-03,28.89,-0.078832
138,GVR,2025,3,2025-09-30,2025-12-01,26.70,NaN
139,GVR,2025,4,2025-12-31,NaT,NaN,NaN
140,HDB,2021,1,2021-03-31,2021-06-01,11.18,-0.067524
141,HDB,2021,2,2021-06-30,2021-09-01,10.45,0.220652
142,HDB,2021,3,2021-09-30,2021-12-01,13.03,-0.082348
143,HDB,2021,4,2021-12-31,2022-04-01,12.00,-0.119347
144,HDB,2022,1,2022-03-31,2022-06-01,10.65,0.009346
145,HDB,2022,2,2022-06-30,2022-09-05,10.75,-0.280576
146,HDB,2022,3,2022-09-30,2022-12-01,8.12,0.193141
147,HDB,2022,4,2022-12-31,2023-04-03,9.85,0.013112
148,HDB,2023,1,2023-03-31,2023-06-01,9.98,0.055543
149,HDB,2023,2,2023-06-30,2023-09-05,10.55,0.062463
150,HDB,2023,3,2023-09-30,2023-12-01,11.23,0.276714
151,HDB,2023,4,2023-12-31,2024-04-01,14.81,0.000000
152,HDB,2024,1,2024-03-31,2024-06-03,14.81,0.161742
153,HDB,2024,2,2024-06-30,2024-09-04,17.41,-0.064653
154,HDB,2024,3,2024-09-30,2024-12-02,16.32,0.058893
155,HDB,2024,4,2024-12-31,2025-04-01,17.31,-0.038274
156,HDB,2025,1,2025-03-31,2025-06-02,16.66,0.426452
157,HDB,2025,2,2025-06-30,2025-09-03,25.52,-0.049398
158,HDB,2025,3,2025-09-30,2025-12-01,24.29,NaN
159,HDB,2025,4,2025-12-31,NaT,NaN,NaN
160,HPG,2021,1,2021-03-31,2021-06-01,31.82,-0.120418
161,HPG,2021,2,2021-06-30,2021-09-01,28.21,-0.004263
162,HPG,2021,3,2021-09-30,2021-12-01,28.09,-0.069654
163,HPG,2021,4,2021-12-31,2022-04-01,26.20,-0.285649
164,HPG,2022,1,2022-03-31,2022-06-01,19.69,-0.083647
165,HPG,2022,2,2022-06-30,2022-09-05,18.11,-0.272521
166,HPG,2022,3,2022-09-30,2022-12-01,13.79,0.143004
167,HPG,2022,4,2022-12-31,2023-04-03,15.91,0.018680
168,HPG,2023,1,2023-03-31,2023-06-01,16.21,0.261747
169,HPG,2023,2,2023-06-30,2023-09-05,21.06,-0.032821
170,HPG,2023,3,2023-09-30,2023-12-01,20.38,0.112207
171,HPG,2023,4,2023-12-31,2024-04-01,22.80,0.058352
172,HPG,2024,1,2024-03-31,2024-06-03,24.17,-0.138687
173,HPG,2024,2,2024-06-30,2024-09-04,21.04,0.063528
174,HPG,2024,3,2024-09-30,2024-12-02,22.42,0.003562
175,HPG,2024,4,2024-12-31,2025-04-01,22.50,-0.055278
176,HPG,2025,1,2025-03-31,2025-06-02,21.29,0.279310
177,HPG,2025,2,2025-06-30,2025-09-03,28.15,-0.060403
178,HPG,2025,3,2025-09-30,2025-12-01,26.50,NaN
179,HPG,2025,4,2025-12-31,NaT,NaN,NaN
180,LPB,2021,1,2021-03-31,2021-06-01,12.87,-0.149757
181,LPB,2021,2,2021-06-30,2021-09-01,11.08,0.000000
182,LPB,2021,3,2021-09-30,2021-12-01,11.08,-0.035833
183,LPB,2021,4,2021-12-31,2022-04-01,10.69,-0.283637
184,LPB,2022,1,2022-03-31,2022-06-01,8.05,0.053217
185,LPB,2022,2,2022-06-30,2022-09-05,8.49,-0.184444
186,LPB,2022,3,2022-09-30,2022-12-01,7.06,0.307318
187,LPB,2022,4,2022-12-31,2023-04-03,9.60,-0.052390
188,LPB,2023,1,2023-03-31,2023-06-01,9.11,0.343193
189,LPB,2023,2,2023-06-30,2023-09-05,12.84,-0.051129
190,LPB,2023,3,2023-09-30,2023-12-01,12.20,0.123233
191,LPB,2023,4,2023-12-31,2024-04-01,13.80,0.399651
192,LPB,2024,1,2024-03-31,2024-06-03,20.58,0.178427
193,LPB,2024,2,2024-06-30,2024-09-04,24.60,0.075153
194,LPB,2024,3,2024-09-30,2024-12-02,26.52,0.159630
195,LPB,2024,4,2024-12-31,2025-04-01,31.11,0.028207
196,LPB,2025,1,2025-03-31,2025-06-02,32.00,0.334238
197,LPB,2025,2,2025-06-30,2025-09-03,44.70,0.069142
198,LPB,2025,3,2025-09-30,2025-12-01,47.90,NaN
199,LPB,2025,4,2025-12-31,NaT,NaN,NaN
200,MBB,2021,1,2021-03-31,2021-06-01,12.77,-0.014196
201,MBB,2021,2,2021-06-30,2021-09-01,12.59,0.056364
202,MBB,2021,3,2021-09-30,2021-12-01,13.32,0.120782
203,MBB,2021,4,2021-12-31,2022-04-01,15.03,-0.187525
204,MBB,2022,1,2022-03-31,2022-06-01,12.46,0.025358
205,MBB,2022,2,2022-06-30,2022-09-05,12.78,-0.281960
206,MBB,2022,3,2022-09-30,2022-12-01,9.64,0.049580
207,MBB,2022,4,2022-12-31,2023-04-03,10.13,0.004924
208,MBB,2023,1,2023-03-31,2023-06-01,10.18,0.183467
209,MBB,2023,2,2023-06-30,2023-09-05,12.23,-0.072914
210,MBB,2023,3,2023-09-30,2023-12-01,11.37,0.335341
211,MBB,2023,4,2023-12-31,2024-04-01,15.90,-0.075076
212,MBB,2024,1,2024-03-31,2024-06-03,14.75,0.076961
213,MBB,2024,2,2024-06-30,2024-09-04,15.93,-0.010729
214,MBB,2024,3,2024-09-30,2024-12-02,15.76,0.158131
215,MBB,2024,4,2024-12-31,2025-04-01,18.46,0.000000
216,MBB,2025,1,2025-03-31,2025-06-02,18.46,0.432542
217,MBB,2025,2,2025-06-30,2025-09-03,28.45,-0.203996
218,MBB,2025,3,2025-09-30,2025-12-01,23.20,NaN
219,MBB,2025,4,2025-12-31,NaT,NaN,NaN
220,MSN,2021,1,2021-03-31,2021-06-01,87.62,0.228289
221,MSN,2021,2,2021-06-30,2021-09-01,110.09,0.117369
222,MSN,2021,3,2021-09-30,2021-12-01,123.80,-0.021308
223,MSN,2021,4,2021-12-31,2022-04-01,121.19,-0.059759
224,MSN,2022,1,2022-03-31,2022-06-01,114.16,0.011670
225,MSN,2022,2,2022-06-30,2022-09-05,115.50,-0.154151
226,MSN,2022,3,2022-09-30,2022-12-01,99.00,-0.253915
227,MSN,2022,4,2022-12-31,2023-04-03,76.80,-0.067320
228,MSN,2023,1,2023-03-31,2023-06-01,71.80,0.126719
229,MSN,2023,2,2023-06-30,2023-09-05,81.50,-0.281566
230,MSN,2023,3,2023-09-30,2023-12-01,61.50,0.176887
231,MSN,2023,4,2023-12-31,2024-04-01,73.40,0.056931
232,MSN,2024,1,2024-03-31,2024-06-03,77.70,-0.031375
233,MSN,2024,2,2024-06-30,2024-09-04,75.30,-0.036515
234,MSN,2024,3,2024-09-30,2024-12-02,72.60,-0.092284
235,MSN,2024,4,2024-12-31,2025-04-01,66.20,-0.063934
236,MSN,2025,1,2025-03-31,2025-06-02,62.10,0.290095
237,MSN,2025,2,2025-06-30,2025-09-03,83.00,-0.051928
238,MSN,2025,3,2025-09-30,2025-12-01,78.80,NaN
239,MSN,2025,4,2025-12-31,NaT,NaN,NaN
240,MWG,2021,1,2021-03-31,2021-06-01,43.65,0.194655
241,MWG,2021,2,2021-06-30,2021-09-01,53.03,0.231444
242,MWG,2021,3,2021-09-30,2021-12-01,66.84,0.116119
243,MWG,2021,4,2021-12-31,2022-04-01,75.07,-0.069640
244,MWG,2022,1,2022-03-31,2022-06-01,70.02,0.002995
245,MWG,2022,2,2022-06-30,2022-09-05,70.23,-0.498279
246,MWG,2022,3,2022-09-30,2022-12-01,42.67,-0.121716
247,MWG,2022,4,2022-12-31,2023-04-03,37.78,0.007647
248,MWG,2023,1,2023-03-31,2023-06-01,38.07,0.332939
249,MWG,2023,2,2023-06-30,2023-09-05,53.11,-0.337414
250,MWG,2023,3,2023-09-30,2023-12-01,37.90,0.282457
251,MWG,2023,4,2023-12-31,2024-04-01,50.27,0.219197
252,MWG,2024,1,2024-03-31,2024-06-03,62.59,0.084665
253,MWG,2024,2,2024-06-30,2024-09-04,68.12,-0.134623
254,MWG,2024,3,2024-09-30,2024-12-02,59.54,-0.030179
255,MWG,2024,4,2024-12-31,2025-04-01,57.77,0.040039
256,MWG,2025,1,2025-03-31,2025-06-02,60.13,0.231589
257,MWG,2025,2,2025-06-30,2025-09-03,75.80,0.053928
258,MWG,2025,3,2025-09-30,2025-12-01,80.00,NaN
259,MWG,2025,4,2025-12-31,NaT,NaN,NaN
260,PLX,2021,1,2021-03-31,2021-06-01,47.03,-0.053052
261,PLX,2021,2,2021-06-30,2021-09-01,44.60,0.066568
262,PLX,2021,3,2021-09-30,2021-12-01,47.67,0.014578
263,PLX,2021,4,2021-12-31,2022-04-01,48.37,-0.213781
264,PLX,2022,1,2022-03-31,2022-06-01,39.06,-0.060145
265,PLX,2022,2,2022-06-30,2022-09-05,36.78,-0.259622
266,PLX,2022,3,2022-09-30,2022-12-01,28.37,0.190396
267,PLX,2022,4,2022-12-31,2023-04-03,34.32,-0.001458
268,PLX,2023,1,2023-03-31,2023-06-01,34.27,0.044515
269,PLX,2023,2,2023-06-30,2023-09-05,35.83,-0.088967
270,PLX,2023,3,2023-09-30,2023-12-01,32.78,0.061808
271,PLX,2023,4,2023-12-31,2024-04-01,34.87,0.141245
272,PLX,2024,1,2024-03-31,2024-06-03,40.16,0.124401
273,PLX,2024,2,2024-06-30,2024-09-04,45.48,-0.167654
274,PLX,2024,3,2024-09-30,2024-12-02,38.46,0.013686
275,PLX,2024,4,2024-12-31,2025-04-01,38.99,-0.123796
276,PLX,2025,1,2025-03-31,2025-06-02,34.45,0.059172
277,PLX,2025,2,2025-06-30,2025-09-03,36.55,-0.059172
278,PLX,2025,3,2025-09-30,2025-12-01,34.45,NaN
279,PLX,2025,4,2025-12-31,NaT,NaN,NaN
280,SAB,2021,1,2021-03-31,2021-06-01,60.18,-0.035002
281,SAB,2021,2,2021-06-30,2021-09-01,58.11,0.051156
282,SAB,2021,3,2021-09-30,2021-12-01,61.16,0.076464
283,SAB,2021,4,2021-12-31,2022-04-01,66.02,-0.076628
284,SAB,2022,1,2022-03-31,2022-06-01,61.15,0.205358
285,SAB,2022,2,2022-06-30,2022-09-05,75.09,-0.069335
286,SAB,2022,3,2022-09-30,2022-12-01,70.06,0.051058
287,SAB,2022,4,2022-12-31,2023-04-03,73.73,-0.134675
288,SAB,2023,1,2023-03-31,2023-06-01,64.44,0.013257
289,SAB,2023,2,2023-06-30,2023-09-05,65.30,-0.200058
290,SAB,2023,3,2023-09-30,2023-12-01,53.46,-0.111072
291,SAB,2023,4,2023-12-31,2024-04-01,47.84,0.044761
292,SAB,2024,1,2024-03-31,2024-06-03,50.03,-0.004407
293,SAB,2024,2,2024-06-30,2024-09-04,49.81,-0.017621
294,SAB,2024,3,2024-09-30,2024-12-02,48.94,-0.094657
295,SAB,2024,4,2024-12-31,2025-04-01,44.52,-0.004051
296,SAB,2025,1,2025-03-31,2025-06-02,44.34,0.002478
297,SAB,2025,2,2025-06-30,2025-09-03,44.45,0.055783
298,SAB,2025,3,2025-09-30,2025-12-01,47.00,NaN
299,SAB,2025,4,2025-12-31,NaT,NaN,NaN
300,SHB,2021,1,2021-03-31,2021-06-01,13.59,-0.141235
301,SHB,2021,2,2021-06-30,2021-09-01,11.80,0.078999
302,SHB,2021,3,2021-09-30,2021-12-01,12.77,-0.063860
303,SHB,2021,4,2021-12-31,2022-04-01,11.98,-0.397567
304,SHB,2022,1,2022-03-31,2022-06-01,8.05,0.040176
305,SHB,2022,2,2022-06-30,2022-09-05,8.38,-0.232736
306,SHB,2022,3,2022-09-30,2022-12-01,6.64,0.049937
307,SHB,2022,4,2022-12-31,2023-04-03,6.98,0.048927
308,SHB,2023,1,2023-03-31,2023-06-01,7.33,0.239114
309,SHB,2023,2,2023-06-30,2023-09-05,9.31,-0.154151
310,SHB,2023,3,2023-09-30,2023-12-01,7.98,0.053671
311,SHB,2023,4,2023-12-31,2024-04-01,8.42,0.017658
312,SHB,2024,1,2024-03-31,2024-06-03,8.57,-0.070077
313,SHB,2024,2,2024-06-30,2024-09-04,7.99,-0.010063
314,SHB,2024,3,2024-09-30,2024-12-02,7.91,0.294611
315,SHB,2024,4,2024-12-31,2025-04-01,10.62,0.095139
316,SHB,2025,1,2025-03-31,2025-06-02,11.68,0.489189
317,SHB,2025,2,2025-06-30,2025-09-03,19.05,-0.113854
318,SHB,2025,3,2025-09-30,2025-12-01,17.00,NaN
319,SHB,2025,4,2025-12-31,NaT,NaN,NaN
320,SSB,2021,1,2021-03-31,2021-06-01,20.19,-0.043012
321,SSB,2021,2,2021-06-30,2021-09-01,19.34,0.157543
322,SSB,2021,3,2021-09-30,2021-12-01,22.64,0.041952
323,SSB,2021,4,2021-12-31,2022-04-01,23.61,-0.138809
324,SSB,2022,1,2022-03-31,2022-06-01,20.55,0.130729
325,SSB,2022,2,2022-06-30,2022-09-05,23.42,-0.054399
326,SSB,2022,3,2022-09-30,2022-12-01,22.18,0.041939
327,SSB,2022,4,2022-12-31,2023-04-03,23.13,-0.033857
328,SSB,2023,1,2023-03-31,2023-06-01,22.36,0.079492
329,SSB,2023,2,2023-06-30,2023-09-05,24.21,-0.192034
330,SSB,2023,3,2023-09-30,2023-12-01,19.98,-0.026885
331,SSB,2023,4,2023-12-31,2024-04-01,19.45,-0.022882
332,SSB,2024,1,2024-03-31,2024-06-03,19.01,-0.027194
333,SSB,2024,2,2024-06-30,2024-09-04,18.50,-0.087503
334,SSB,2024,3,2024-09-30,2024-12-02,16.95,0.142707
335,SSB,2024,4,2024-12-31,2025-04-01,19.55,-0.055205
336,SSB,2025,1,2025-03-31,2025-06-02,18.50,0.133869
337,SSB,2025,2,2025-06-30,2025-09-03,21.15,-0.206731
338,SSB,2025,3,2025-09-30,2025-12-01,17.20,NaN
339,SSB,2025,4,2025-12-31,NaT,NaN,NaN
340,SSI,2021,1,2021-03-31,2021-06-01,17.71,0.355488
341,SSI,2021,2,2021-06-30,2021-09-01,25.27,0.275038
342,SSI,2021,3,2021-09-30,2021-12-01,33.27,-0.251959
343,SSI,2021,4,2021-12-31,2022-04-01,25.86,-0.372937
344,SSI,2022,1,2022-03-31,2022-06-01,17.81,-0.119117
345,SSI,2022,2,2022-06-30,2022-09-05,15.81,-0.264137
346,SSI,2022,3,2022-09-30,2022-12-01,12.14,0.189980
347,SSI,2022,4,2022-12-31,2023-04-03,14.68,0.063985
348,SSI,2023,1,2023-03-31,2023-06-01,15.65,0.390660
349,SSI,2023,2,2023-06-30,2023-09-05,23.13,-0.041489
350,SSI,2023,3,2023-09-30,2023-12-01,22.19,0.192856
351,SSI,2023,4,2023-12-31,2024-04-01,26.91,-0.091786
352,SSI,2024,1,2024-03-31,2024-06-03,24.55,-0.065653
353,SSI,2024,2,2024-06-30,2024-09-04,22.99,-0.056826
354,SSI,2024,3,2024-09-30,2024-12-02,21.72,0.063329
355,SSI,2024,4,2024-12-31,2025-04-01,23.14,-0.094662
356,SSI,2025,1,2025-03-31,2025-06-02,21.05,0.556693
357,SSI,2025,2,2025-06-30,2025-09-03,36.73,-0.231139
358,SSI,2025,3,2025-09-30,2025-12-01,29.15,NaN
359,SSI,2025,4,2025-12-31,NaT,NaN,NaN
360,STB,2021,1,2021-03-31,2021-06-01,32.40,-0.174941
361,STB,2021,2,2021-06-30,2021-09-01,27.20,0.094642
362,STB,2021,3,2021-09-30,2021-12-01,29.90,0.074108
363,STB,2021,4,2021-12-31,2022-04-01,32.20,-0.369624
364,STB,2022,1,2022-03-31,2022-06-01,22.25,0.104461
365,STB,2022,2,2022-06-30,2022-09-05,24.70,-0.236389
366,STB,2022,3,2022-09-30,2022-12-01,19.50,0.316120
367,STB,2022,4,2022-12-31,2023-04-03,26.75,0.045670
368,STB,2023,1,2023-03-31,2023-06-01,28.00,0.155171
369,STB,2023,2,2023-06-30,2023-09-05,32.70,-0.173189
370,STB,2023,3,2023-09-30,2023-12-01,27.50,0.132622
371,STB,2023,4,2023-12-31,2024-04-01,31.40,-0.053979
372,STB,2024,1,2024-03-31,2024-06-03,29.75,0.011696
373,STB,2024,2,2024-06-30,2024-09-04,30.10,0.095008
374,STB,2024,3,2024-09-30,2024-12-02,33.10,0.181818
375,STB,2024,4,2024-12-31,2025-04-01,39.70,0.051545
376,STB,2025,1,2025-03-31,2025-06-02,41.80,0.297798
377,STB,2025,2,2025-06-30,2025-09-03,56.30,-0.138874
378,STB,2025,3,2025-09-30,2025-12-01,49.00,NaN
379,STB,2025,4,2025-12-31,NaT,NaN,NaN
380,TCB,2021,1,2021-03-31,2021-06-01,25.08,-0.094433
381,TCB,2021,2,2021-06-30,2021-09-01,22.82,0.081188
382,TCB,2021,3,2021-09-30,2021-12-01,24.75,-0.040822
383,TCB,2021,4,2021-12-31,2022-04-01,23.76,-0.310959
384,TCB,2022,1,2022-03-31,2022-06-01,17.41,0.046024
385,TCB,2022,2,2022-06-30,2022-09-05,18.23,-0.342745
386,TCB,2022,3,2022-09-30,2022-12-01,12.94,0.067240
387,TCB,2022,4,2022-12-31,2023-04-03,13.84,0.033396
388,TCB,2023,1,2023-03-31,2023-06-01,14.31,0.144218

In [ ]:
print(master_df.isnull().sum().to_string())

In [7]:
df_finrl.head(5)

,ticker,yearReport,lengthReport,TOTAL ASSETS (Bn. VND),Cash and cash equivalents (Bn. VND),Balances with the SBV,Placements with and loans to other credit institutions,"Trading Securities, net",Trading Securities,Provision for diminution in value of Trading Securities,Derivatives and other financial liabilities,"Loans and advances to customers, net",Loans and advances to customers,Less: Provision for losses on loans and advances to customers,Investment Securities,Available-for Sales Securities,Held-to-Maturity Securities,Less: Provision for diminution in value of investment securities,Long-term investments (Bn. VND),Investments in associate companies,Other long-term assets (Bn. VND),Less: Provision for diminuation in value of long term investments,Fixed assets (Bn. VND),Tangible fixed assets,Intagible fixed assets,Investment in properties,Other Assets,TOTAL RESOURCES (Bn. VND),LIABILITIES (Bn. VND),Due to Gov and borrowings from SBV,Deposits and borrowings from other credit institutions,Deposits from customers,_Derivatives and other financial liabilities,"Funds received from Gov, international and other institutions",Convertible bonds/CDs and other valuable papers issued,Other liabilities,OWNER'S EQUITY(Bn.VND),Capital,Reserves,Foreign Currency Difference reserve,Undistributed earnings (Bn. VND),Paid-in capital (Bn. VND),MINORITY INTERESTS,Revenue (Bn. VND),Revenue YoY (%),Attribute to parent company (Bn. VND),Attribute to parent company YoY (%),Interest and Similar Income,Interest and Similar Expenses,Net Interest Income,Fees and Comission Income,Fees and Comission Expenses,Net Fee and Commission Income,Net gain (loss) from foreign currency and gold dealings,Net gain (loss) from trading of trading securities,Net gain (loss) from disposal of investment securities,Net Other income/(expenses),Other expenses,Net Other income/expenses,Dividends received,Total operating revenue,General & Admin Expenses,Operating Profit before Provision,Provision for credit losses,Profit before tax,Tax For the Year,Business income tax - current,Business income tax - deferred,Net Profit For the Year,Attributable to parent company,EPS_basis,Profits from other activities,Operating profit before changes in working capital,Net Cash Flows from Operating Activities before BIT,Payment from reserves,Purchase of fixed assets,Gain on Dividend,Net Cash Flows from Investing Activities,Increase in charter captial,Cash flows from financial activities,Net increase/decrease in cash and cash equivalents,Cash and cash equivalents,Foreign exchange differences Adjustment,Cash and Cash Equivalents at the end of period,Net cash inflows/outflows from operating activities,Proceeds from disposal of fixed assets,Investment in other entities,Proceeds from divestment in other entities,Dividends paid,Debt/Equity,Fixed Asset-To-Equity,Owners' Equity/Charter Capital,Net Profit Margin (%),ROE (%),ROIC (%),ROA (%),Dividend yield (%),Financial Leverage,Market Capital (Bn. VND),Outstanding Share (Mil. Shares),P/E,P/B,P/S,P/Cash Flow,EPS (VND),BVPS (VND),Quarter_Time,Investment in joint ventures,Leased assets,Difference upon Assets Revaluation,Minority Interest,Other Reserves,CURRENT ASSETS (Bn. VND),Short-term investments (Bn. VND),Accounts receivable (Bn. VND),Net Inventories,Other current assets,LONG-TERM ASSETS (Bn. VND),Other non-current assets,Current liabilities (Bn. VND),Long-term liabilities (Bn. VND),Capital and reserves (Bn. VND),Prepayments to suppliers (Bn. VND),Short-term loans receivables (Bn. VND),"Inventories, Net (Bn. VND)",Other current assets (Bn. VND),Investment and development funds (Bn. VND),Common shares (Bn. VND),Advances from customers (Bn. VND),Short-term borrowings (Bn. VND),Good will (Bn. VND),Long-term prepayments (Bn. VND),Other long-term receivables (Bn. VND),Long-term trade receivables (Bn. VND),Financial Income,Interest Expenses,Sales,Sales deductions,Net Sales,Cost of Sales,Gross Profit,Financial Expenses,Gain/(loss) from joint ventures,Selling Expenses,Operating Profit/Loss,Other income,Net income from associated companies,Other Income/Expenses,Net other income/expenses,Net Profit/Loss before tax,Depreciation and Amortisation,Unrealized foreign exchange gain/loss,Profit/Loss from investing activities,Interest Expense,Increase/Decrease in receivables,Increase/Decrease in inventories,Increase/Decrease in payables,Increase/Decrease in prepaid expenses,Interest paid,Business Income Tax paid,Other receipts from operating activities,Other payments on operating activities,"Loans granted, purchases of debt instruments (Bn. VND)","Collection of loans, proceeds from sales of debts instruments (Bn. VND)",Payments for share repurchases,Proceeds from borrowings,Repayment of borrowings,(ST+LT borrowings)/Equity,Asset Turnover,Fixed Asset Turnover,Days Sales Outstanding,Days Inventory Outstanding,Days Payable Outstanding,Cash Cycle,Inventory Turnover,EBIT Margin (%),Gross Profit Margin (%),EBITDA (Bn. VND),EBIT (Bn. VND),Current Ratio,Cash Ratio,Quick Ratio,Interest Coverage,EV/EBITDA,Long-term loans receivables (Bn. VND),Goodwill,Budget sources and other funds,Long-term borrowings (Bn. VND),Finance lease principal payments,Interest income and dividends,Profit/Loss from disposal of fixed assets,Convertible bonds (Bn. VND),_Increase/Decrease in receivables,_Increase/Decrease in payables,adj_close_q,actual_price_date,y_return
0,ACB,2021,1,449514732000000,6037588000000,2.023257e+13,2.774639e+13,4.419502e+12,4.529892e+12,-1.103900e+11,1.355030e+11,3.207550e+14,3.243111e+14,-3.556125e+12,5.889389e+13,1.029406e+13,4.893283e+13,-3.330030e+11,99549000000,2.967000e+09,1.018270e+11,-5.245000e+09,3720662000000,2.664580e+12,1.056082e+12,2.160270e+11,7.258052e+12,449514732000000,411585397000000,0.0,2.033560e+13,3.522177e+14,0.0,1.082490e+11,2.038404e+13,1.853985e+13,37929335000000,2.188736e+13,5.742084e+12,-2.229000e+09,10302116000000,21615585000000,0.0,8314894000000,0.059140,2483401000000,0.615690,8.314894e+12,-3.675322e+12,4.639572e+12,8.801050e+11,-2.548980e+11,6.252070e+11,1.961400e+11,1.134920e+11,4.893900e+10,2.460460e+11,-1.970990e+11,4.894700e+10,3.080000e+09,5.675377e+12,-1965297000000,3.710080e+12,-6.057610e+11,3104319000000,-6.209180e+11,-710036000000,8.911800e+10,2483401000000,2483401000000,1149.0,-8.770000e+09,2.856723e+12,1.264041e+12,-570000000.0,-9.305200e+10,3.494000e+09,5.966100e+10,0.0,0.000000e+00,1.323132e+12,4.602207e+13,-2.229000e+09,4.734297e+13,1.263471e+12,7.660000e+08,0.000000e+00,0.0,0.0,10.851374,0.098095,0.738405,0.535265,0.251710,0.0,0.020190,0.0,11.851374,8.848880e+13,2.701948e+09,10.254612,2.332991,4.547574,10.852700,919.114998,14037.773468,2021-03-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15.80,2021-06-01,-0.051293
1,ACB,2021,2,471275438000000,6870892000000,2.191232e+13,2.898854e+13,1.027074e+13,1.037530e+13,-1.045540e+11,8.203800e+10,3.368276e+14,3.416675e+14,-4.839861e+12,5.552839e+13,9.535454e+12,4.625312e+13,-2.601850e+11,87912000000,2.967000e+09,1.018270e+11,-1.688200e+10,3703279000000,2.628026e+12,1.075253e+12,2.160270e+11,6.787651e+12,471275438000000,430895193000000,0.0,2.708596e+13,3.584741e+14,0.0,1.006530e+11,2.745532e+13,1.777912e+13,40380245000000,2.188736e+13,5.742084e+12,1.044600e+10,12740351000000,21615585000000,0.0,8653369000000,0.136707,2588235000000,0.700934,8.653369e+12,-3.662982e+12,4.990387e+12,1.186356e+12,-2.999770e+11,8.863790e+11,2.315240e+11,9.166800e+10,4.470900e+10,1.747080e+11,-1.956200e+11,-2.091200e+10,3.462000e+09,6.227217e+12,-1592538000000,4.634679e+12,-1.386245e+12,3248434000000,-6.601990e+11,-591994000000,-6.820500e+10,2588235000000,2588235000000,673.0,-9.344200e+10,4.062063e+12,2.310412e+12,-380000000.0,-2.294380e+11,2.822000e+09,-2.247300e+11,0.0,0.000000e+00,2.085302e+12,4.734297e+13,1.267500e+10,4.944095e+13,2.310032e+12,1.886000e+09,0.000000e+00,0.0,0.0,10.670941,0.091710,0.786119,0.518644,0.264411,0.0,0.021739,0.0,11.670941,8.808351e+13,2.701948e+09,9.084754,2.181351,4.081043,13.602313,957.914411,14944.863439,2021-06-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15.01,2021-09-01,0.045581
2,ACB,2021,3,479308753000000,7010081000000,3.353294e+13,2.867565e+13,1.015199e+13,1.023994e+13,-8.794700e+10,6.398200e+10,3.309113e+14,3.364916e+14,-5.580344e+12,5.853372e+13,8.886513e+12,4.980765e+13,-1.604380e+11,88068000000,2.967000e+09,1.018270e+11,-1.672600e+10,3646321000000,2.581210e+12,1.065111e+12,2.160270e+11,6.478715e+12,479308753000000,436825317000000,0.0,2.032417e+13,3.657705e+14,0.0,9.379900e+10,3.246994e+13,1.816694e+13,42483436000000,2.729126e+13,5.742084e+12,1.102200e+10,9439070000000,27019481000000,0.0,8290513000000,0.045349,2102615000000,0.013517,8.290513e+12,-3.770002e+12,4.520511e+12,8.970880e+11,-2.615290e+11,6.355590e+11,2.059330e+11,1.834810e+11,9.203800e+10,1.483820e+11,-1.060550e+11,4.232700e+10,1.033300e+10,5.690182e+12,-2254497000000,3.435685e+12,-8.200860e+11,2615599000000,-5.129840e+11,-558745000000,4.576100e+10,2102615000000,2102615000000,323.0,-9.741000e+09,3.356786e+12,1.272229e+13,-275000000.0,-5.034900e+10,9.939000e+09,-4.041000e+10,0.0,0.000000e+00,1.268161e+13,4.944095e+13,5.760000e+08,6.212313e+13,1.272202e+13,0.000000e+00,0.000000e+00,0.0,0.0,10.282250,0.085829,0.827064,0.465128,0.248943,0.0,0.021086,0.0,11.282250,8.862390e+13,2.701948e+09,9.114127,2.086081,3.889029,3.461299,778.184829,15723.261447,2021-09-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15.71,2021-12-01,-0.003188
3,ACB,2021,4,527769944000000,7509877000000,3.234957e+13,4.981878e+13,1.125973e+13,1.132537e+13,-6.564000e+10,2.265450e+11,3.560510e+14,3.619125e+14,-5.861588e+12,5.947460e+13,9.739539e+12,4.974307e+13,-8.006000e+09,171925000000,0.000000e+00,2.993170e+11,-1.273920e+11,3762548000000,2.685070e+12,1.077478e+12,2.160270e+11,6.929387e+12,527769944000000,482869035000000,0.0,5.439394e+13,3.799207e+14,0.0,8.606600e+10,3.054788e+13,1.792048e+13,44900909000000,2.729126e+13,7.164297e+12,0.000000e+00,10445352000000,27019481000000,0.0,8455034000000,-0.000777,2428495000000,-0.047478,8.455034e+12,-3.660712e+12,4.794322e+12,1.062911e+12,-3.160930e+11,7.468180e+11,2.379590e+11,6.131900e+10,5.836500e+10,1.340230e+11,-6.492200e+10,6.910100e+10,3.337000e+09,5.971221e+12,-2417444000000,3.553777e+12,-5.240170e+11,3029760000000,-6.012650e+11,-528304000000,-7.296100e+10,2428495000000,2428495000000,898.0,1.698900e+10,2.051001e+12,2.363064e+13,-258000000.0,-2.632610e+11,5.724000e+09,-2.569240e+11,0.0,-2.884000e+12,2.048946e+13,6.212313e+13,-1.102200e+10,8.260157e+13,2.363038e+13,6.130000e+08,0.000000e+00,0.0,0.0,10.754104,0.083797,0.874127,0.506536,0.239026,0.0,0.019753,0.0,11.754104,8.349020e+13,2.701948e+09,8.694409,1.859432,3.543125,2.091129,898.794104,16617.976273,2021-12-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15.66,2022-04-01,-0.070773
4,ACB,2022,1,528636428000000,6281931000000,1.820813e+13,5.433781e+13,5.068428e+12,5.159447e+12,-9.101900e+10,9.240800e+10,3.741246e+14,3.799830e+14,-5.858314e+12,5.871020e+13,1.063452e+13,4.807909e+13,-3.409000e+09,207771000000,0.000000e+00,3.098370e+11,-1.020660e+11,3678381000000,2.641814e+12,1.036567e+12,2.160270e+11,7.710713e+12,528636428000000,480433095000000,0.0,4.432346e+13,3.860509e+14,0.0,7.917600e+10,3.094967e+13,1.902988e+13,48203333000000,2.729126e+13,7.164297e+12,1.488900e+10,13732887000000,27019481000000,0.0,9053845000000,0.088871,3287535000000,0.323804,9.053845e+12,-3.613173e+12,5.440672e+12,1.024894e+12,-2.857350e+11,7.391590e+11,3.033670e+11,-1.122400e+10,6.505000e+09,4.290990e+11,-5.990800e+10,3.691910e+11,2.093000e+09,6.849763e+12,-2738601000000,4.111162e+12,2.843000e+09,4114005000000,-8.264700e+11,-982622000000,1.561520e+11,3287535000000,3287535000000,1217.0,3.326900e+10,3.593628e+12,-8.504080e+12,-399000000.0,-8.349400e+10,2.507000e+09,-9.060400e+10,0.0,0.000000e+00,-8.595083e+12,8.260157e+13,1.488900e+10,7.402137e+13,-8.504479e+12,9.030000e+08,-1.052000e+10,0.0,0.0,9.966802,0.076310,0.938418,0.604252,0.236563,0.0,0.020741,0.0,10.966802,8.105844e+13,3.377435e+09,7.788928,1.681594,3.276627,2.687797,973.382140,14272.171532,2022-03-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14.59,2022-06-01,-0.015890

In [8]:
import os

file_name = "raw_fundermental_data.csv"

# Kiểm tra nếu file tồn tại thì xoá
if os.path.exists(file_name):
    os.remove(file_name)
    print(f"Đã xoá file cũ: {file_name}")

# Lưu lại file mới
df_finrl.to_csv(file_name, index=False)
print(f"Đã lưu file mới: {file_name}")

Đã xoá file cũ: raw_fundermental_data.csv
Đã lưu file mới: raw_fundermental_data.csv

In [9]:
df_finrl = pd.read_csv("raw_fundermental_data.csv")
df_finrl.head(5)

,ticker,yearReport,lengthReport,TOTAL ASSETS (Bn. VND),Cash and cash equivalents (Bn. VND),Balances with the SBV,Placements with and loans to other credit institutions,"Trading Securities, net",Trading Securities,Provision for diminution in value of Trading Securities,Derivatives and other financial liabilities,"Loans and advances to customers, net",Loans and advances to customers,Less: Provision for losses on loans and advances to customers,Investment Securities,Available-for Sales Securities,Held-to-Maturity Securities,Less: Provision for diminution in value of investment securities,Long-term investments (Bn. VND),Investments in associate companies,Other long-term assets (Bn. VND),Less: Provision for diminuation in value of long term investments,Fixed assets (Bn. VND),Tangible fixed assets,Intagible fixed assets,Investment in properties,Other Assets,TOTAL RESOURCES (Bn. VND),LIABILITIES (Bn. VND),Due to Gov and borrowings from SBV,Deposits and borrowings from other credit institutions,Deposits from customers,_Derivatives and other financial liabilities,"Funds received from Gov, international and other institutions",Convertible bonds/CDs and other valuable papers issued,Other liabilities,OWNER'S EQUITY(Bn.VND),Capital,Reserves,Foreign Currency Difference reserve,Undistributed earnings (Bn. VND),Paid-in capital (Bn. VND),MINORITY INTERESTS,Revenue (Bn. VND),Revenue YoY (%),Attribute to parent company (Bn. VND),Attribute to parent company YoY (%),Interest and Similar Income,Interest and Similar Expenses,Net Interest Income,Fees and Comission Income,Fees and Comission Expenses,Net Fee and Commission Income,Net gain (loss) from foreign currency and gold dealings,Net gain (loss) from trading of trading securities,Net gain (loss) from disposal of investment securities,Net Other income/(expenses),Other expenses,Net Other income/expenses,Dividends received,Total operating revenue,General & Admin Expenses,Operating Profit before Provision,Provision for credit losses,Profit before tax,Tax For the Year,Business income tax - current,Business income tax - deferred,Net Profit For the Year,Attributable to parent company,EPS_basis,Profits from other activities,Operating profit before changes in working capital,Net Cash Flows from Operating Activities before BIT,Payment from reserves,Purchase of fixed assets,Gain on Dividend,Net Cash Flows from Investing Activities,Increase in charter captial,Cash flows from financial activities,Net increase/decrease in cash and cash equivalents,Cash and cash equivalents,Foreign exchange differences Adjustment,Cash and Cash Equivalents at the end of period,Net cash inflows/outflows from operating activities,Proceeds from disposal of fixed assets,Investment in other entities,Proceeds from divestment in other entities,Dividends paid,Debt/Equity,Fixed Asset-To-Equity,Owners' Equity/Charter Capital,Net Profit Margin (%),ROE (%),ROIC (%),ROA (%),Dividend yield (%),Financial Leverage,Market Capital (Bn. VND),Outstanding Share (Mil. Shares),P/E,P/B,P/S,P/Cash Flow,EPS (VND),BVPS (VND),Quarter_Time,Investment in joint ventures,Leased assets,Difference upon Assets Revaluation,Minority Interest,Other Reserves,CURRENT ASSETS (Bn. VND),Short-term investments (Bn. VND),Accounts receivable (Bn. VND),Net Inventories,Other current assets,LONG-TERM ASSETS (Bn. VND),Other non-current assets,Current liabilities (Bn. VND),Long-term liabilities (Bn. VND),Capital and reserves (Bn. VND),Prepayments to suppliers (Bn. VND),Short-term loans receivables (Bn. VND),"Inventories, Net (Bn. VND)",Other current assets (Bn. VND),Investment and development funds (Bn. VND),Common shares (Bn. VND),Advances from customers (Bn. VND),Short-term borrowings (Bn. VND),Good will (Bn. VND),Long-term prepayments (Bn. VND),Other long-term receivables (Bn. VND),Long-term trade receivables (Bn. VND),Financial Income,Interest Expenses,Sales,Sales deductions,Net Sales,Cost of Sales,Gross Profit,Financial Expenses,Gain/(loss) from joint ventures,Selling Expenses,Operating Profit/Loss,Other income,Net income from associated companies,Other Income/Expenses,Net other income/expenses,Net Profit/Loss before tax,Depreciation and Amortisation,Unrealized foreign exchange gain/loss,Profit/Loss from investing activities,Interest Expense,Increase/Decrease in receivables,Increase/Decrease in inventories,Increase/Decrease in payables,Increase/Decrease in prepaid expenses,Interest paid,Business Income Tax paid,Other receipts from operating activities,Other payments on operating activities,"Loans granted, purchases of debt instruments (Bn. VND)","Collection of loans, proceeds from sales of debts instruments (Bn. VND)",Payments for share repurchases,Proceeds from borrowings,Repayment of borrowings,(ST+LT borrowings)/Equity,Asset Turnover,Fixed Asset Turnover,Days Sales Outstanding,Days Inventory Outstanding,Days Payable Outstanding,Cash Cycle,Inventory Turnover,EBIT Margin (%),Gross Profit Margin (%),EBITDA (Bn. VND),EBIT (Bn. VND),Current Ratio,Cash Ratio,Quick Ratio,Interest Coverage,EV/EBITDA,Long-term loans receivables (Bn. VND),Goodwill,Budget sources and other funds,Long-term borrowings (Bn. VND),Finance lease principal payments,Interest income and dividends,Profit/Loss from disposal of fixed assets,Convertible bonds (Bn. VND),_Increase/Decrease in receivables,_Increase/Decrease in payables,adj_close_q,actual_price_date,y_return
0,ACB,2021,1,449514732000000,6037588000000,2.023257e+13,2.774639e+13,4.419502e+12,4.529892e+12,-1.103900e+11,1.355030e+11,3.207550e+14,3.243111e+14,-3.556125e+12,5.889389e+13,1.029406e+13,4.893283e+13,-3.330030e+11,99549000000,2.967000e+09,1.018270e+11,-5.245000e+09,3720662000000,2.664580e+12,1.056082e+12,2.160270e+11,7.258052e+12,449514732000000,411585397000000,0.0,2.033560e+13,3.522177e+14,0.0,1.082490e+11,2.038404e+13,1.853985e+13,37929335000000,2.188736e+13,5.742084e+12,-2.229000e+09,10302116000000,21615585000000,0.0,8314894000000,0.059140,2483401000000,0.615690,8.314894e+12,-3.675322e+12,4.639572e+12,8.801050e+11,-2.548980e+11,6.252070e+11,1.961400e+11,1.134920e+11,4.893900e+10,2.460460e+11,-1.970990e+11,4.894700e+10,3.080000e+09,5.675377e+12,-1965297000000,3.710080e+12,-6.057610e+11,3104319000000,-6.209180e+11,-710036000000,8.911800e+10,2483401000000,2483401000000,1149.0,-8.770000e+09,2.856723e+12,1.264041e+12,-570000000.0,-9.305200e+10,3.494000e+09,5.966100e+10,0.0,0.000000e+00,1.323132e+12,4.602207e+13,-2.229000e+09,4.734297e+13,1.263471e+12,7.660000e+08,0.000000e+00,0.0,0.0,10.851374,0.098095,0.738405,0.535265,0.251710,0.0,0.020190,0.0,11.851374,8.848880e+13,2.701948e+09,10.254612,2.332991,4.547574,10.852700,919.114998,14037.773468,2021-03-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15.80,2021-06-01,-0.051293
1,ACB,2021,2,471275438000000,6870892000000,2.191232e+13,2.898854e+13,1.027074e+13,1.037530e+13,-1.045540e+11,8.203800e+10,3.368276e+14,3.416675e+14,-4.839861e+12,5.552839e+13,9.535454e+12,4.625312e+13,-2.601850e+11,87912000000,2.967000e+09,1.018270e+11,-1.688200e+10,3703279000000,2.628026e+12,1.075253e+12,2.160270e+11,6.787651e+12,471275438000000,430895193000000,0.0,2.708596e+13,3.584741e+14,0.0,1.006530e+11,2.745532e+13,1.777912e+13,40380245000000,2.188736e+13,5.742084e+12,1.044600e+10,12740351000000,21615585000000,0.0,8653369000000,0.136707,2588235000000,0.700934,8.653369e+12,-3.662982e+12,4.990387e+12,1.186356e+12,-2.999770e+11,8.863790e+11,2.315240e+11,9.166800e+10,4.470900e+10,1.747080e+11,-1.956200e+11,-2.091200e+10,3.462000e+09,6.227217e+12,-1592538000000,4.634679e+12,-1.386245e+12,3248434000000,-6.601990e+11,-591994000000,-6.820500e+10,2588235000000,2588235000000,673.0,-9.344200e+10,4.062063e+12,2.310412e+12,-380000000.0,-2.294380e+11,2.822000e+09,-2.247300e+11,0.0,0.000000e+00,2.085302e+12,4.734297e+13,1.267500e+10,4.944095e+13,2.310032e+12,1.886000e+09,0.000000e+00,0.0,0.0,10.670941,0.091710,0.786119,0.518644,0.264411,0.0,0.021739,0.0,11.670941,8.808351e+13,2.701948e+09,9.084754,2.181351,4.081043,13.602313,957.914411,14944.863439,2021-06-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15.01,2021-09-01,0.045581
2,ACB,2021,3,479308753000000,7010081000000,3.353294e+13,2.867565e+13,1.015199e+13,1.023994e+13,-8.794700e+10,6.398200e+10,3.309113e+14,3.364916e+14,-5.580344e+12,5.853372e+13,8.886513e+12,4.980765e+13,-1.604380e+11,88068000000,2.967000e+09,1.018270e+11,-1.672600e+10,3646321000000,2.581210e+12,1.065111e+12,2.160270e+11,6.478715e+12,479308753000000,436825317000000,0.0,2.032417e+13,3.657705e+14,0.0,9.379900e+10,3.246994e+13,1.816694e+13,42483436000000,2.729126e+13,5.742084e+12,1.102200e+10,9439070000000,27019481000000,0.0,8290513000000,0.045349,2102615000000,0.013517,8.290513e+12,-3.770002e+12,4.520511e+12,8.970880e+11,-2.615290e+11,6.355590e+11,2.059330e+11,1.834810e+11,9.203800e+10,1.483820e+11,-1.060550e+11,4.232700e+10,1.033300e+10,5.690182e+12,-2254497000000,3.435685e+12,-8.200860e+11,2615599000000,-5.129840e+11,-558745000000,4.576100e+10,2102615000000,2102615000000,323.0,-9.741000e+09,3.356786e+12,1.272229e+13,-275000000.0,-5.034900e+10,9.939000e+09,-4.041000e+10,0.0,0.000000e+00,1.268161e+13,4.944095e+13,5.760000e+08,6.212313e+13,1.272202e+13,0.000000e+00,0.000000e+00,0.0,0.0,10.282250,0.085829,0.827064,0.465128,0.248943,0.0,0.021086,0.0,11.282250,8.862390e+13,2.701948e+09,9.114127,2.086081,3.889029,3.461299,778.184829,15723.261447,2021-09-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15.71,2021-12-01,-0.003188
3,ACB,2021,4,527769944000000,7509877000000,3.234957e+13,4.981878e+13,1.125973e+13,1.132537e+13,-6.564000e+10,2.265450e+11,3.560510e+14,3.619125e+14,-5.861588e+12,5.947460e+13,9.739539e+12,4.974307e+13,-8.006000e+09,171925000000,0.000000e+00,2.993170e+11,-1.273920e+11,3762548000000,2.685070e+12,1.077478e+12,2.160270e+11,6.929387e+12,527769944000000,482869035000000,0.0,5.439394e+13,3.799207e+14,0.0,8.606600e+10,3.054788e+13,1.792048e+13,44900909000000,2.729126e+13,7.164297e+12,0.000000e+00,10445352000000,27019481000000,0.0,8455034000000,-0.000777,2428495000000,-0.047478,8.455034e+12,-3.660712e+12,4.794322e+12,1.062911e+12,-3.160930e+11,7.468180e+11,2.379590e+11,6.131900e+10,5.836500e+10,1.340230e+11,-6.492200e+10,6.910100e+10,3.337000e+09,5.971221e+12,-2417444000000,3.553777e+12,-5.240170e+11,3029760000000,-6.012650e+11,-528304000000,-7.296100e+10,2428495000000,2428495000000,898.0,1.698900e+10,2.051001e+12,2.363064e+13,-258000000.0,-2.632610e+11,5.724000e+09,-2.569240e+11,0.0,-2.884000e+12,2.048946e+13,6.212313e+13,-1.102200e+10,8.260157e+13,2.363038e+13,6.130000e+08,0.000000e+00,0.0,0.0,10.754104,0.083797,0.874127,0.506536,0.239026,0.0,0.019753,0.0,11.754104,8.349020e+13,2.701948e+09,8.694409,1.859432,3.543125,2.091129,898.794104,16617.976273,2021-12-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15.66,2022-04-01,-0.070773
4,ACB,2022,1,528636428000000,6281931000000,1.820813e+13,5.433781e+13,5.068428e+12,5.159447e+12,-9.101900e+10,9.240800e+10,3.741246e+14,3.799830e+14,-5.858314e+12,5.871020e+13,1.063452e+13,4.807909e+13,-3.409000e+09,207771000000,0.000000e+00,3.098370e+11,-1.020660e+11,3678381000000,2.641814e+12,1.036567e+12,2.160270e+11,7.710713e+12,528636428000000,480433095000000,0.0,4.432346e+13,3.860509e+14,0.0,7.917600e+10,3.094967e+13,1.902988e+13,48203333000000,2.729126e+13,7.164297e+12,1.488900e+10,13732887000000,27019481000000,0.0,9053845000000,0.088871,3287535000000,0.323804,9.053845e+12,-3.613173e+12,5.440672e+12,1.024894e+12,-2.857350e+11,7.391590e+11,3.033670e+11,-1.122400e+10,6.505000e+09,4.290990e+11,-5.990800e+10,3.691910e+11,2.093000e+09,6.849763e+12,-2738601000000,4.111162e+12,2.843000e+09,4114005000000,-8.264700e+11,-982622000000,1.561520e+11,3287535000000,3287535000000,1217.0,3.326900e+10,3.593628e+12,-8.504080e+12,-399000000.0,-8.349400e+10,2.507000e+09,-9.060400e+10,0.0,0.000000e+00,-8.595083e+12,8.260157e+13,1.488900e+10,7.402137e+13,-8.504479e+12,9.030000e+08,-1.052000e+10,0.0,0.0,9.966802,0.076310,0.938418,0.604252,0.236563,0.0,0.020741,0.0,10.966802,8.105844e+13,3.377435e+09,7.788928,1.681594,3.276627,2.687797,973.382140,14272.171532,2022-03-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14.59,2022-06-01,-0.015890